### ISSUE TITLE
Loss of timestamp in EventData?? And cal.serve(...) changed!!!

### ISSUE THREAD

**Issue by JoelParke** [sebbo2002/ical-generator#101]
I noticed in upgrading from 0.2.10 to the 'latest', that the interface of EventData is now:
```
        /**
         * Information used to create calendar events
         */
        interface EventData {
            start: moment.Moment | Date;
            summary: string;
            id?: string;
            uid?: string;
            end?: moment.Moment | Date;
            stamp?: moment.Moment | Date;
            description?: string;
            location?: string;
            url?: string;
            sequence?: number;
            allDay?: boolean;
            floating?: boolean;
            repeating?: RepeatingData;
            htmlDescription?: string;
            organizer?: string | PersonData;
            attendees?: AttendeeData[];
            alarms?: AlarmData[];
            status?: string;
            timezone?: string;
        }
```
AND timestamp is now gone.  Is this replaced by stamp? which I suspect?
Also cal.serve(res) now fails... 
In the upgrade is this now `cal.serve(res, ???)` and what is this filename?
Thanks!

**Comment by sebbo2002** [comment]
- `timestamp/stamp` both are fine as `stamp` is an alias of `timestamp`. It just got lost during the rewrite. This should be fixed in `index.d.ts`.
- `cal.serve()` fails: What's the exception thrown? Or why do you think this method works not as expected?
- Filename of `cal.serve()`: It's the filename used when downloading the calendar file. The default value is `calendar.ics`, so if you set it to null or undefined, the download would be named `calendar.ics`.

**Comment by JoelParke** [comment]
Thanks very much for the quick response!
I am attempting to determine why the calendar is not being served.  If keep seeing (bad gateway - 502).  But the lines being shown from the error throw makes no sense yet... 
Stay tuned...

**Comment by sebbo2002** [comment]
Okay, please reopen if anything is unclear.

**Comment by JoelParke** [comment]
It took a while (because the line numbers in the code were very unclear) to learn that I had an undefined variable which was throwing an error.  SO the good news is that the ical.serve is working properly!  Thanks.

I would perhaps suggest that you shift the ICalCalendar definition to:

```
   /**
     * The calendar object containing all event data
     */
    class ICalCalendar {
      constructor(data?: CalendarData);
      ...
      ...
      ---> serve(respone: Response, filename?: string): ICalCalendar;
      ...
      clear(): ICalCalendar;
 ```
to allow the typescript to accept a ical.serve(res) without any errors.
Thanks very much for the work, no need to reopen.
