### ISSUE TITLE
TypeScript transpile breaks

### ISSUE THREAD

**Issue by straczowski** [sebbo2002/ical-generator#103]
Hello together 

i am not able to run `tsc` in my project

i got the following Error:

```
$ tsc

node_modules/ical-generator/index.d.ts(257,3): error TS2666: Exports and export assignments are not permitted in module augmentations.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! support-calendar-calculator@0.0.1 tsc: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the support-calendar-calculator@0.0.1 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

i am using
`ical-generator`:`^1.0.3`
`typescript`:`2.6.2`
any idea how i can fi this?

thx in advance :)

**Comment by sebbo2002** [comment]
Since I do not use a typescript, I cannot answer your question with the necessary technical knowledge. Looks like an error in index.d.ts:257. Feel free to send a pull request in case it's an error in our definition file. Thank you.

**Comment by evelynhathaway** [comment]
I am new to TypeScript; however, I noticed that pulling down #128 resolved this error. My best guess as to why is given [this comment](https://github.com/Microsoft/TypeScript/issues/11133#issuecomment-249673608), is that the imports before the module declaration make TypeScript assume that it's a module argumentation.
