### ISSUE TITLE
Repeating exclusions don't handle all day very well.

### ISSUE THREAD

**Issue by newtang** [sebbo2002/ical-generator#107]
If you have a repeating all day event with an exclusion, it won't work very well. I've tried importing the result in Google Calendar and iCal and the the exclusion is always ignored.  I believe in the repeating exclusion code, there needs to be a check for `if (this._data.allDay) `  and to prepend the date value with `VALUE=DATE:`

**Comment by sebbo2002** [comment]
Will look into this for on of the next versions, thank you!

**Comment by sebbo2002** [comment]
Oh. Just saw you your PR #108. Will have a look into this next week, thank you.
