### ISSUE TITLE
GEO 

### ISSUE THREAD

**Issue by 1000i100** [sebbo2002/ical-generator#112]
As specified, there is not only location but also geo position (gps) :
https://tools.ietf.org/html/rfc5545#section-3.8.1.6
It look like : `GEO:37.386013;-122.082932`

It look easy to add : A unit test similar to location and probably the same in src, with few contols : 
geo must be 2 floats with ';' between them.

**Comment by Sparticuz** [comment]
Does #142 close this or is there more work that needs to be done?

**Comment by sebbo2002** [comment]
@Sparticuz No, should be all done here. Thank you.

@1000i100 If I'm missing something, please reopen this issue.
