### ISSUE TITLE
Problem : Exports and export assignments are not permitted in module augmentations

### ISSUE THREAD

**Issue by medbejimbj** [sebbo2002/ical-generator#114]
Hi,
I use ical in my TS nodejs project like this  in my service file : 

import * as ical from 'ical-generator';
after :
const cal = ical({
            name: 'project-name',
        });
and I use createEvent function like in documentation.

It works fine in dev mode , when I build my project I get this message : 

node_modules/ical-generator/index.d.ts:257:3 - error TS2666: Exports and export assignments are not permitted in module augmentations.

257   export = ICalGenerator;

Thanks,

**Comment by sebbo2002** [comment]
Since I don't use a type script, I'm unfortunately not able to provide support for it. Therefore I have to close the issue. The file `index.d.ts` was added by a pull request I tried to keep updated manually. If the file is faulty, please provide a new pull request.

**Comment by medbejimbj** [comment]
I found an interim solution for that, which is to import the dist directory :
`import * as ical from 'ical-generator/dist';`
The time to make a pull request.
