### ISSUE TITLE
Organizer EMAIL= in addition to mailto:

### ISSUE THREAD

**Issue by VSchlattinger** [sebbo2002/ical-generator#119]
I would like to create an .ics file where the `organizer` has an `EMAIL` attribute in addition to the `mailto:` value.

For example, when I send an invitation with Apple Calendar, the `organizer` line in the .ics file will look like this:

```
ORGANIZER;CN="<Name>";EMAIL=<EMAIL>:mailto:<SOMEID>@imip.me.com
```

where `<Name>` is my name, `<EMAIL>` is my actual email address (e.g. example@gmail.com) and `<SOMEID>` is a seemingly random sequence of characters.

The point is that this way, the organizer's actual email address can be displayed, while the `mailto:` value is different and can point to our server, so that we get notified when the invitation is accepted.

Does `ical-generator` currently support that? If not, would you consider adding this functionality?

**Comment by sebbo2002** [comment]
No, this feature is not implemented yet. But it sounds to me like that should change. I'll leave this here and implement it if I can find the time. Otherwise, of course, pull requests are also welcome. To do this, `Attendee` would have to be extended by a `mailto` method and the updated generation code.

**Comment by VSchlattinger** [comment]
I created a pull request for this: https://github.com/sebbo2002/ical-generator/pull/120

Please take a look and tell me if there is something I should change.

**Comment by visiongeist** [comment]
@VSchlattinger I know out of scope.. but stupid question, which server are you using for synchronisation?
