### ISSUE TITLE
attendees

### ISSUE THREAD

**Issue by J-Katzen** [sebbo2002/ical-generator#12]
Would be nice if this could support attendees.

**Comment by AzadMemon** [comment]
+1. This would make your ical stand out among the rest. I haven't been able to find one that supports attendees.

**Comment by slava-tre** [comment]
need attendees as well =(

**Comment by sebbo2002** [comment]
I will add attendees after my exams. Stay tuned…

**Comment by sebbo2002** [comment]
I just pushed ical-generator 0.2.0 with a new API and attendees :tada:
But the old 0.1.x API *should* still work…
