### ISSUE TITLE
Support for repeating bySetPos

### ISSUE THREAD

**Issue by farhadSagar** [sebbo2002/ical-generator#123]
Currently don't see the support for bySetPos for repeating events. It would be nice to have that support.

**Comment by farhadSagar** [comment]
@sebbo2002 I have a pr ready for review, can you add me as a Collaborators so that I can push and create a PR?

**Comment by farhadSagar** [comment]
@sebbo2002 PR for this issue: https://github.com/sebbo2002/ical-generator/pull/124

**Comment by sebbo2002** [comment]
Merged PR, so closing this one here. Thanks.
