### ISSUE TITLE
Having some difficulty with timezones

### ISSUE THREAD

**Issue by ScottChapman** [sebbo2002/ical-generator#125]
So I am generating an iCal feed, and subscribing to it from my google calendar.

My ical/events look like:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Myco//MyProd//EN
NAME:My Name
X-WR-CALNAME:MyName
TIMEZONE-ID:America/New_York
X-WR-TIMEZONE:America/New_York
REFRESH-INTERVAL;VALUE=DURATION:PT4320H
X-PUBLISHED-TTL:PT4320H
BEGIN:VEVENT
UID:1542575184345@foo.com
SEQUENCE:0
DTSTAMP:20181120T000000Z
DTSTART;TZID=America/New_York:20181120T000000
DTEND;TZID=America/New_York:20181121T000000
SUMMARY:Vacation
DESCRIPTION:Pre-PreThanksgiving
END:VEVENT
```

What's happening is my event is showing up starting at 7PM one day and ends 7PM the next day:
![image](https://user-images.githubusercontent.com/1517892/48678583-41969280-eb53-11e8-8173-e92e5148cdb7.png)

Any ideas?

**Comment by sebbo2002** [comment]
For all day events you need to set the [`allDay` option](https://github.com/sebbo2002/ical-generator#alldayboolean-allday).

**Comment by ScottChapman** [comment]
Right, but my question was more about why there is an apparent timeshift. I don't understand why all my time zones are the same (including my client location) and the times are all midnight, but the times appear as 7pm.

I do realize that a way to "fix" this is to use full-day events (which I am now doing anyway), but I still see this shift for events that are not full-day events.

**Comment by sebbo2002** [comment]
Hmm. The ical seems to look quite fine for me, but I have no Google Account to test this. You may want to test it with UTC timestamps, maybe that will work…

**Comment by ScottChapman** [comment]
yea, I know right?

I'll try UTC for everything and see how that behaves.

Thanks!
