### ISSUE TITLE
Support X-* properties

### ISSUE THREAD

**Issue by dploeger** [sebbo2002/ical-generator#129]
It would be great, if ical-generator would support vendor-specific X-* properties (I'm currently using a platform, that uses X-PROP-REGION, X-PROP-FEES and other properties)

**Comment by dploeger** [comment]
@sebbo2002 I could create a PR for this if you're basically willing to accept it. Or do you want to check the voting on it first?

**Comment by sebbo2002** [comment]
I think it's a very custom feature which is required by very few people. As I want ical-generator to be a small library which does not claim to be the right tool for every usecase, I would like to prefer seeing others demanding this feature before merging it. Feel free to fork this repo to fulfil your needs if you can't wait.

**Comment by dploeger** [comment]
Okay, thanks. I will go with ical-toolkit then. They already have this feature.

**Comment by sebbo2002** [comment]
If it's okay for you I'll reopen this issue to track further demand.

**Comment by dploeger** [comment]
Yes, sure.

**Comment by filetvignon** [comment]
I guess this is pretty useful if you want to make your ics file compatible with outlook?

**Comment by Sparticuz** [comment]
Instead of creating methods for each X- property, I think it would be a good idea to have cal.custom("PROP-REGION",value) that would add X-PROP-REGION with the value to the object. That would give us total customization and low code impact.

**Comment by Fristi** [comment]
Would love to see this

**Comment by sebbo2002** [comment]
[Just added a x() method for alarm-, calendar- and event objects](https://github.com/sebbo2002/ical-generator/tree/feature/x). Could you take a look at this, please? Does that meet your requirements or is something missing?

**Comment by sebbo2002** [comment]
Since no one has contacted me, I just assume that it will be all right. I merged the feature after develop and will release it soon. It will be available from 1.9.0.
