### ISSUE TITLE
Repeating event not showing up on OS X calendar upon importing

### ISSUE THREAD

**Issue by lshe7842** [sebbo2002/ical-generator#130]
Hey there, getting issue when importing an ics file generated by ical-generator. What I'm generating is a series of repeating events like this:

`cal.createEvent({
              start: moment('2018-12-04T06:00:00'),
              summary: 'Test repeat',
              description: 'Test how iCal repeat works',
              location: 'Home',
          }).repeating({
            freq: 'HOURLY',
            interval: 5,
            count: 8
        });`

I validated the ics file using some online validator with no issues. However, upon importing this ics file into my mac calendar, nothing shows up.

Thanks.

**Comment by lshe7842** [comment]
Update: this doesn't seem to be an issue with this package. It seems the calendar app itself doesn't support this. Also tried to import into google calendar, get the same result.

Any clues?

**Comment by sebbo2002** [comment]
According to my information, many clients unfortunately only support daily repetition and greater. I had already thought about removing this in ical-generator. But since it is a valid ical, but I left it in.

**Comment by lshe7842** [comment]
Yep. Further investigation I did proved that both ios and google calendar don't support recurrence more frequent than daily. Thanks for closing this @sebbo2002 .
