### ISSUE TITLE
Accepted types for uid

### ISSUE THREAD

**Issue by evelynhathaway** [sebbo2002/ical-generator#133]
Re: [Comment on PR #132](https://github.com/sebbo2002/ical-generator/pull/132/files/333a55bb7825a9af4012af183bfc535302c6dd19#r239693611)

I noticed the type definitions for `uid`'s method parameters and returned values were always strings, and I assumed the docs were incorrect, but then I later saw there is a [test](https://github.com/sebbo2002/ical-generator/blob/develop/test/test_event.js#L56) for the number to be passed in and returned back out; however, the assertion is less clear to me as it is a deprecated non-strict equals.

Before submitting a PR for changes to the types, I wanted to make sure that a number is a valid argument and it should implicitly convert it to a string when it's generated rather than explicitly on assigning to it's data object.

**Comment by sebbo2002** [comment]
> I noticed the type definitions for uid's method parameters and returned values were always strings, and I assumed the docs were incorrect, but then I later saw there is a test for the number to be passed in and returned back out

The support for integers in uid() is from the first version of this module and has been allowed until now. I don't recommend it, but without good reason I couldn't bring myself to change this behavior so far.

> the assertion is less clear to me as it is a deprecated non-strict equals

That's right, you could actually change that.


> Before submitting a PR for changes to the types, I wanted to make sure that a number is a valid argument and it should implicitly convert it to a string when it's generated rather than explicitly on assigning to it's data object

In order to maintain backward compatibility, I would not want to change anything about this procedure unless there is a reason that I am overlooking right now. But then I would like to remove integers completely and only allow strings. I think that's a much cleaner solution.

**Comment by evelynhathaway** [comment]
> That's right, you could actually change that.

Will do. 😄

> I would not want to change anything about this procedure unless there is a reason that I am overlooking right now.

Yeah, I agree. I will leave the method untouched unless you think that there is something to gain by changing the number to a string before assigning to `_data` so that the method always returns a string.

**Comment by evelynhathaway** [comment]
I am back from holiday, and so I made two PRs that resolve the topics discussed in this issue. Let me know if you have any questions. 😄

**Comment by sebbo2002** [comment]
Nice one, I'll try to have a look at it this weekend…

**Comment by sebbo2002** [comment]
Both perfect pull requests, thanks for your collaboration… ❤️
