### ISSUE TITLE
TypeError: __webpack_require__(...).writeFile is not a function

### ISSUE THREAD

**Issue by ztretterath** [sebbo2002/ical-generator#149]
I am trying to sync my in-app calendar data with iCal. 

Mapping over my schedule events, creating events with `cal` then saving.

The error I am seeing makes me think I do not have `fs` installed (fs.writeFile) but I do.

Thank you in advance for any insight.

```
    const cal = ical({
      timezone: 'UTC',
      name: schedule.name,
      domain: 'gomaxone.com'
    })

    await Promise.all(scheduleEvents.map(event => {
      cal.createEvent({
        start: event.startDate,
        end: event.endDate,
        summary: event.title,
        description: event.description,
        location: event.location
      });
    }))

    const stringifiedData = cal.toString();
    cal.save(stringifiedData);
```

**Comment by sebbo2002** [comment]
`cal.createEvent` is sync, so you woun't need your `Promise.all`. Please note that [save()](https://github.com/sebbo2002/ical-generator#savestring-file-function-cb) has different arguments. Also, if you don't use catch save() errors, use saveSync() instead.

 ```js
cal.saveSync('./filename.ics')
```

**Comment by ztretterath** [comment]
@sebbo2002 - this is great, thank you for your prompt response and assistance.
