### ISSUE TITLE
Daylight saving time changes during the recurring sequence

### ISSUE THREAD

**Issue by SergijeRaz** [sebbo2002/ical-generator#150]
## Current behavior
In Outlook or Thunderbird, if the daylight saving time change date is in the middle of the recurring sequence, all appointments after it are one hour off. Also, if any of the appointments in that sequence after the time change are excluded, they dont dissapear in the calendar since the times are off by an hour so they aren't recognized. If the beginning of the sequence is after that date, or both the beginning and the end are before that date, the appointments work fine.
(I am saving the dates in UTC time format)

## Expected behavior
All the appointments should have the same start and end time even if the daylight saving time change date is during the recurring sequence.

## Minimal reproduction of the problem with instructions
Create a recurring sequence with appointments that begins before the daylight saving time change date and ends after.

## Environment
```
ical-generator: "1.5.0",
Angular: 7,
node: v8.9.4,
Calendar: Outlook, Thunderbird
```

**Comment by sebbo2002** [comment]
That shouldn't be the case if you use `timezone()` to set the event's timezone correctly. Otherwise it's UTC and woun't respond to your local time changes.

**Comment by sebbo2002** [comment]
Close the issue due to inactivity. Hope the problem has been solved elsewhere.
