### ISSUE TITLE
Events: Timezone (using & property setting)

### ISSUE THREAD

**Issue by NickCis** [sebbo2002/ical-generator#152]
I have several question regarding timezone setting for specific properties.

I've checked that the library for [`DTSTART`](https://github.com/sebbo2002/ical-generator/blob/aa59dddaf0224fe39ea46afea94d6dc0ba991d9c/src/event.js#L978) and [`DTEND`](https://github.com/sebbo2002/ical-generator/blob/aa59dddaf0224fe39ea46afea94d6dc0ba991d9c/src/event.js#L980) properties is using the calendar timezone, shouldn't use instead the event's timezone?:
```js
g += ICalTools.formatDateTZ(this.timezone(), 'DTSTART', this._data.start, this._data) + '\r\n';
if (this._data.end) {
    g += ICalTools.formatDateTZ(this.timezone(), 'DTEND', this._data.end, this._data) + '\r\n';
}
```
If the event hasn't a timezone set, it will [default to the calendar's one](https://github.com/sebbo2002/ical-generator/blob/aa59dddaf0224fe39ea46afea94d6dc0ba991d9c/src/event.js#L258).

I'm not sure if other event's properties (`UNTIL`, `RECURRENCE-ID`, `EXDATE`, etc), should follow the same timezone logic.

In addition, it will be great to allow to set different timezones (`TZID` properties) to `DTSTART` and `DTEND`. I'm willing to send the necessary PRs, but, it will be great to discuss the api. I think that there are two approaches that could be used:

1. Define a _DateTime_ interface (eg: `{ dateTime: Date / String, timezone: String }`), allow to set `start` and `end` with that new interface (being retrocompatible with the current api). And use that timezone (fallbacking to the event's timezone) when writing the `DTSTART` and `DTEND` properties.
2. Add two properties: `startTimezone` and `endTimezone`. Use that properties for `DTSTART` and `DTEND` respectively (fallbacking to the event's timezone).  

More over, i've recently send a [PR to allow to set timezone for `EXDATE`](https://github.com/sebbo2002/ical-generator/pull/151). The problem with it, is that is doesn't allow to set different timezones per exclusion (which is something i'm now needing to). This could be fixed, if each exclusion follows the _DateTime_ interface mentioned before.

---

To give some context, I'm working on a oss [tool](https://github.com/NickCis/google-icalendar-sync) that allows you to export events from google calendar (in an ical format) when the organization has forbid calendar sharing.

Google's calendar allows you to set different timezones for most of it's properties (eg: `DTSTART` and `DTEND` could be shown in different timezones). And when using google's ical output (from a mail that has this activated), it creates this output:
```ical
BEGIN:VEVENT
DTSTART;TZID=America/Argentina/Buenos_Aires:20190326T100000
DTEND;TZID=Europe/Berlin:20190326T143000
RRULE:FREQ=WEEKLY;WKST=MO;INTERVAL=2;BYDAY=TU
EXDATE;TZID=America/Argentina/Buenos_Aires:20190604T100000
EXDATE;TZID=America/Argentina/Buenos_Aires:20190423T100000
DTSTAMP:20190317T012117Z
UID:XXXXXXXXXXX@google.com
CREATED:20190317T011705Z
DESCRIPTION:
LAST-MODIFIED:20190317T012053Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Test: todos los martes
TRANSP:OPAQUE
END:VEVENT
```

---

As I've said before, I'm willing to send the necessary PRs. But, I think that it will be better to reach to an agreement about the API before I start implementing it.

**Comment by sebbo2002** [comment]
> I've checked that the library for DTSTART and DTEND properties is using the calendar timezone, shouldn't use instead the event's timezone?

It does? It just uses the calendar's timezone in case we don't have a valid timezone set.


> I'm not sure if other event's properties (UNTIL, RECURRENCE-ID, EXDATE, etc), should follow the same timezone logic.

They should. See below.


> In addition, it will be great to allow to set different timezones (TZID properties) to DTSTART and DTEND. I'm willing to send the necessary PRs, but, it will be great to discuss the api. I think that there are two approaches that could be used:
> 
> - Define a DateTime interface (eg: { dateTime: Date / String, timezone: String }), allow to set start and end with that new interface (being retrocompatible with the current api). And use that timezone (fallbacking to the event's timezone) when writing the DTSTART and DTEND properties.
> - Add two properties: startTimezone and endTimezone. Use that properties for DTSTART and DTEND respectively (fallbacking to the event's timezone).

I thought about that as well. I prefer to use moment-timezone, so we don't need a custom interface here as moment-timezone is already supported. Since that would be a breaking change, I'm just putting it off a little bit. Sorry for that.

**Comment by NickCis** [comment]
> It does? It just uses the calendar's timezone in case we don't have a valid timezone set.

I was referring to #154 . It's already fixed.

> I thought about that as well. I prefer to use moment-timezone, so we don't need a custom interface here as moment-timezone is already supported. Since that would be a breaking change, I'm just putting it off a little bit. Sorry for that.

Oh, I didn't know that the `moment` object was storing the timezone data, I thought it was only for formatting purposes. It's a great idea to use that `moment-timezone` object.

The idea will be to use the `moment` object's timezone, if it is set (I'll check for that data via the `.tz()` method). If the `moment`'s object hasn't got timezone information fallback to the current behavior (use event's timezone or calendar's). Do you think this is the correct approach?.

**Comment by sebbo2002** [comment]
> The idea will be to use the moment object's timezone, if it is set (I'll check for that data via the .tz() method). If the moment's object hasn't got timezone information fallback to the current behavior (use event's timezone or calendar's). Do you think this is the correct approach?.

Exactly. 😊

**Comment by sebbo2002** [comment]
This topic should have been finished some time ago, because we now use moment-timezone. Do I see that right? I would close the issue. If I miss something, I would like to open it again.
