### ISSUE TITLE
Apple Calendar app support

### ISSUE THREAD

**Issue by ostroffsky** [sebbo2002/ical-generator#157]
It seems like `GEO` field doesn't work properly in apple calendar app until legacy format `X-APPLE-STRUCTURED-LOCATION` is used.

**Comment by sebbo2002** [comment]
Unfortunately, these two fields are not compatible, the Apple format needs the title of the locality and the address in addition to the coordinate. I haven't tried to find out if the field will work on Apple devices without these two information, you might have to do that.

**Comment by focux** [comment]
@sebbo2002 Are you still planning to implement this?

**Comment by sebbo2002** [comment]
@focux I leave the issue open so that I can implement it later when I get to it. At the moment I don't have time to work on it.

**Comment by focux** [comment]
@sebbo2002  I'm already working on a PR. I'll be submitting it in a few minutes.

**Comment by sebbo2002** [comment]
Closing this as @focux's PR just got merged and v1.10.0 has this feature. Thank you all. 😊
