### ISSUE TITLE
Blob is not defined at ICalCalendar.toURL

### ISSUE THREAD

**Issue by tejasvinishelar** [sebbo2002/ical-generator#158]
I want to the download URL of my event.

const cal = ical();
 
		cal.events([
    	{
            start: new Date(),
            end: new Date(new Date().getTime() + 3600000),
            summary: 'Example Event',
            description: 'It works ;)',
            url: 'http://sebbo.net/'
    	}
		]);
 
		cal.events();
		console.log("_____URL______",cal.events());
		
		var url = await cal.toURL()
		await context.sendActivity("Cal url",url);

This is my code.. "I am having Blob is not defined at ICalCalendar.toURL" error
Please can anyone help me to fix this issue.

**Comment by sebbo2002** [comment]
I assume that you use this library client side, not with node.js. Seems like you used an unsupported browser [without blob support](https://caniuse.com/#feat=bloburls). You need a polyfill to support these browsers as well.

Please reopen this issue in case there are related questions.
