### ISSUE TITLE
Passing moment object throws error if versions are different

### ISSUE THREAD

**Issue by dertieran** [sebbo2002/ical-generator#161]
I run into issues when passing a `moment` object that has a different version than the one used by `moment-timezone`.

I have both `moment@2.24.0` and `ical-generator@1.8.0` in my project.
For me this resolves in this dependency tree in a project:

```sh
➜ npm ls moment
├─┬ ical-generator@1.8.0
│ └─┬ moment-timezone@0.5.26
│   └── moment@2.22.2
└── moment@2.24.0
```

_Note: When I tried to do this in isolation it deduped moment correctly :sweat_smile:_

When I then create an event I get an error

```js
const moment = require("moment");
const ical = require("ical-generator");

ical({ events: [{ start: moment() }] });
// => Error: `start` must be a Date or a moment object!
```

The problem is the why you check if the passed `start` is a `moment` object here:
https://github.com/sebbo2002/ical-generator/blob/cb2c184ea419388048089efd24650a656bdf3269/src/event.js#L162-L164

This isn't true if passed `moment` object was created by a different moment version than the one used by `moment-timezone`.

**My suggestion would be to use [`moment.isMoment(start)`](https://momentjs.com/docs/#/query/is-a-moment/) instead.**
I'm also happy to open a PR for this :smile:

**Comment by sebbo2002** [comment]
Ou. Never happend to me, thank you. Have you tried this with `momen.isMoment`? Does that really solve the problem, or does it also result in `false` when it comes to different versions?

Would be happy about a PR, otherwise I'll do it the next days as soon as I get there.

**Comment by dertieran** [comment]
Yea I think that is a rare issue, and I couldn't really reproduce it in a minimal test case by just `npm i moment ical-generator` :sweat_smile:

But I just tested this in the project that produced the above dependency tree:
```js
const moment = require("moment");
const timezone = require("moment-timezone");

console.log(moment.version); // => 2.24.0
console.log(timezone.version); // => 2.22.2

console.log(moment() instanceof timezone); // => false
console.log(timezone.isMoment(moment())); // => true
```

I will open a PR for that, thanks for the quick response.
