### ISSUE TITLE
Include 'busystatus' in class ICalEvent

### ISSUE THREAD

**Issue by cburkhardtBB** [sebbo2002/ical-generator#165]
Although the documentation shows 'busystatus' (busystatus([String busystatus])) as an available method under API > Event, 'busystatus' is not included in the class ICalEvent.

**Comment by sebbo2002** [comment]
[Should be there](https://github.com/sebbo2002/ical-generator/blob/develop/src/event.js#L862). Can you provide a code sample to test with? Which version of ical-generator do you use?

**Comment by cburkhardtBB** [comment]
@sebbo2002 I just installed the latest version of the package because I need to send an .ics file that includes FREEBUSY;FBTYPE=FREE.  

I checked your README before installing the package and saw the that you have 'busystatus' listed as a method with `free, tentative, busy, oof` statuses. (In the **Event** section)

After installing the package, I checked the ical-generator/index.d.ts file that contains the interfaces and classes. However, I cannot find a method under the ICalEvent class for 'busystatus'.

In the image below, you can see that the README on the left shows 'busystatus' as an available method. But on the right side, in the actual code under `class ICalEvent`, 'busystatus' is not listed as a method. 

All other methods listed in the README under the **Event** section are present. 

Am I missing something or is there another way to implement? Thanks! 🙇 

![Screen Shot 2019-10-02 at 4 42 54 PM](https://user-images.githubusercontent.com/31424007/66026617-2a2a8300-e534-11e9-9cc2-eff0596f5742.png)

**Comment by sebbo2002** [comment]
Ah. I see. It's missing in the typescript definition. Really have to find a way to validate these with the current implementation. I hope I can get this fixed in the next few days.

**Comment by sebbo2002** [comment]
@cburkhardtBB Just pushed a fixed version to develop. Can you confirm that it's working there?

**Comment by cburkhardtBB** [comment]
LGTM 👍 I see the definition now and its working for me. Thanks! 🙇
