### ISSUE TITLE
Use with Outlook

### ISSUE THREAD

**Issue by JamilOmar** [sebbo2002/ical-generator#167]
I tried to use it with Outlook , but the html description is not formated properly, any idea how to solve it ?

**Comment by sebbo2002** [comment]
As I don't use Outlook, I'm unable to do any ical client support here. Sorry. Please reopen in case you have an issue with the generated ical content.

**Comment by AndrewLane** [comment]
@sebbo2002 @JamilOmar I have Outlook and have a couple years of experience with the library, if it helps.  I'm willing to help out with this one.

**Comment by AndrewLane** [comment]
@JamilOmar Does your code look like this?

```
var ical = require('ical-generator');
var express = require('express');
var app = express();


app.get("/", function (request, response) {
  response.send(getCal());
});

app.get("/cal.ics", function (request, response) {
  
  response.contentType('text/calendar');
  response.send(getCal());
});


function getCal() {
  var ttlSeconds = 60 * 30; // 30 minutes
  
  var cal = ical({
    domain: 'foo.com', 
    name: 'Some Calendar I have imported',                 
    prodId: {
      company: 'Foo',
      product: 'Bar'
    },
    ttl: ttlSeconds
  });
  
  var fillerContent = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vulputate felis nunc, id gravida metus dignissim id. In hac habitasse platea dictumst. Integer ornare enim sit amet turpis semper laoreet. Duis vitae nibh vitae erat viverra elementum non at libero. Nullam pharetra, magna non semper laoreet, massa lectus malesuada ipsum, ac finibus arcu urna sit amet elit. Sed nec nisl nisl. Integer elementum risus vel nibh ultricies volutpat. In id enim nec nisi faucibus consectetur vitae id orci. Nullam maximus eget magna in viverra. In scelerisque lacinia enim, vitae accumsan nisl pharetra non.';
  var dateOfGeneration = new Date();  
  
  console.log('generating a feed at ' + dateOfGeneration);

  //have it start about an hour from now, but make sure it starts on an "even" time like :00, :15, :30, or :45
  var msInAnHour = 60 * 60 * 1000;
  var msIn15Minutes = 15 * 60 * 1000;
  var msIn24Hours = 24 * 60 * 60 * 1000;
  var startDate = new Date(dateOfGeneration.getTime() + msInAnHour - (dateOfGeneration.getTime() % (msIn15Minutes)));
  var endDate = new Date(startDate.getTime() + msInAnHour);

  var todaysEvent = cal.createEvent({
      start: startDate,
      end: endDate,
      summary: 'Some Event Summary for about an hour from now',    
      description: 'Some event that was generated on ' + dateOfGeneration + '.' + fillerContent,
      location: 'Some location',
      url: 'http://example.com',
      uid: 'foo123',
      status: 'CONFIRMED',
      htmlDescription: 'Some event with <b>markup</b> that was generated on <b>' + dateOfGeneration + '</b>.' + fillerContent
  });  
  
  var tomorrowsEvent = cal.createEvent({
      start: new Date(startDate.getTime() + msIn24Hours),
      end: new Date(endDate.getTime() + msIn24Hours),
      summary: 'Some Event Summary for about a day from now',    
      description: 'Some event that was generated on ' + dateOfGeneration + '.' + fillerContent,
      location: 'Some location',
      url: 'http://example.com',
      uid: 'foo456',
      status: 'TENTATIVE',
      htmlDescription: 'Some event with <b>markup</b> that was generated on <b>' + dateOfGeneration + '</b>.' + fillerContent
  });  
    
  return cal.toString();
}

var listener = app.listen(process.env.PORT, function () {
  console.log('Your app is listening on port ' + listener.address().port);
});
```

I am seeing, at least, bold tags rendered properly in Outlook 365 ProPlus

![image](https://user-images.githubusercontent.com/479232/67290137-b1bd3f00-f4ad-11e9-9992-7bd2686b8cb0.png)

**Comment by vemundeldegard** [comment]
@AndrewLane is the event attachment in the email automatically appearing in your Outlook? I am using the exact same code as you. It is not showing in mine, only when i Click the .ical file. But it is showing on Gmail. 

<img width="887" alt="Skjermbilde 2019-11-18 kl  20 20 35" src="https://user-images.githubusercontent.com/36489034/69082781-1b931f00-0a41-11ea-8683-9c1b6adc3f98.png">
<img width="1104" alt="Skjermbilde 2019-11-18 kl  20 20 52" src="https://user-images.githubusercontent.com/36489034/69082782-1b931f00-0a41-11ea-9e03-977b8c750c10.png">

**Comment by AndrewLane** [comment]
@vemundeldegard I am having trouble understanding your question.  What I have done is create a project on glitch.com to try to replicate this behavior.  See here:

https://glitch.com/~ical-generator-html-description

And then what I'm doing to test in Outlook is to use the "Internet Calendar" option

![image](https://user-images.githubusercontent.com/479232/69166254-f1814180-0ac0-11ea-9caa-3404b98710d8.png)

to test my above Glitch project: https://ical-generator-html-description.glitch.me/cal.ics

I also tried taking the contents of the .ics file and attaching them, and I had success there as well.  So, I'm not sure about the differences between what you are doing and what I'm doing.

![image](https://user-images.githubusercontent.com/479232/69166395-268d9400-0ac1-11ea-91df-207136f8dfe5.png)
