### ISSUE TITLE
Local time to UTC and then back to local time

### ISSUE THREAD

**Issue by rickhernandezio** [sebbo2002/ical-generator#169]
I have a set of events that are in local time. The time the user belongs to, this could be any time zone.

We use this local time to set up the ical events.

```
events.push({
    start: (event.start ? event.start : ''),
    end: (event.end ? event.end : ''),
    summary: (event.title ? event.title : ''),
    description: (event.description ? event.description : ''),
    url: (event.url ? event.url : ''),
    allDay: (event.end ? false : true)
});
```

Then we set the timezone at the ical configuration level.

```
const cal = ical({
    domain: 'saltyslopes.com',
    prodId: { company: 'saltyslopes.com', product: 'calendar-builder' },
    events: events,
    timezone: 'America/Los_Angeles',
    name: calendar.name
});
```

The expected behavior is to have events in PDT timezone.

Actual behavior is they are in UTC in Google Calendar, and Calendar for Mac.

The documentation is a bit vague, should we be setting the timezone at the event level or at the calendar level?  Any help is much appreciated.

**Comment by sebbo2002** [comment]
`floating()` is the way to go, @focux is 100% right. Please reopen in case you have any additions.
