### ISSUE TITLE
Ical doesn't added automatically into calendar

### ISSUE THREAD

**Issue by kevingatp** [sebbo2002/ical-generator#171]
Thankyou for this amazing calendar generator. I've successfully create an .ics file, and save it to my local directory. And the use nodemailer for send email with attached ics file.  The file also shown in the top of email. This is my code:
`

	   var eventObj = {
	    'start' : moment().add(3, 'minutes'),
	    'end' : moment().add(32, 'minutes'),
	    'title' : 'Invitation',
	    'description' : 'This is an Invitation test',
	    'id' : crypto.getRandom(4),
	    'organiser' : {'name' : 'Joe', 'email':'joeprd@gmail.com'},
	    'status' : 'Confirmed'
	}

	cal.createEvent({
	    start: eventObj.start,
	    end: eventObj.end,
	    summary: eventObj.title,
	    description: eventObj.description,
	    location: eventObj.location,
	    uid: eventObj.id,
	    organizer: {
	        name: eventObj.organiser.name,
	        email: eventObj.organiser.email
	    },
	    status: eventObj.status,
	    method: 'PUBLISH',
	    alarms: [
	        {
	            type: 'display',
	            trigger: 60,
	            repeat: 2,
	            interval: 60,
	            description: 'Im a reminder :)'
	        }
	    ],
	});
`

but the calendar doesn't added automatically to receiver calendar. I've tried usinge `cal.events` after `cal.createEvent` and also tried to replace `cal.createEvent` into `cal.events` but nothing work. 

this is what I got from the cal string:
`
		
		BEGIN:VCALENDAR
		VERSION:2.0
		PRODID:-//Joe//Test//EN
		NAME:joe iCal
		X-WR-CALNAME:joe iCal
		BEGIN:VEVENT
		UID:92dc55b9@testjoe.com
		SEQUENCE:0
		DTSTAMP:20191105T153733Z
		DTSTART:20191105T154033Z
		DTEND:20191105T160933Z
		SUMMARY:Invitation
		DESCRIPTION:This is an Invitation Test
		ORGANIZER;CN="Joe":mailto:joeprd@gmail.com
		BEGIN:VALARM
		ACTION:DISPLAY
		TRIGGER:-PT1M
		REPEAT:2
		DURATION:PT1M
		DESCRIPTION:Im a reminder :)
		END:VALARM
		STATUS:CONFIRMED
		END:VEVENT
		END:VCALENDAR
`

Thankyou

**Comment by sebbo2002** [comment]
> but the calendar doesn't added automatically to receiver calendar. I've tried usinge cal.events after cal.createEvent and also tried to replace cal.createEvent into cal.events but nothing work.

This should always return the same calendar.


You probably need an [attendee](https://github.com/sebbo2002/ical-generator#attendee) in your calendar event, but for details you need to have a look in your receiver's calendar logfile. Please reopen in case you have additional questions regarding this library.

**Comment by shashankrepo** [comment]
I'm getting the same issue - not adding automatically to the calendar. My code looks like this.

```
const content = ical({
    domain: 'google.com',
    prodId: '//Google Inc//Google Calendar 70.9054//EN',
    timezone: 'Australia/Brisbane',
    method: 'PUBLISH', //REQUEST
    scale: 'GREGORIAN',
    events: [
      {
        start: moment(),
        status: 'CONFIRMED',
        end: moment().add(1, 'hour'),
        summary: 'Calendar invite test',
        organizer: {
          name: 'Shashank Kumar',
          email: 'xyz@gmail.com',
          mailto: 'xyz@gmail.com'
        },
        location: 'Zoom',
        attendees: [
          {
            email: 'abc@gmail.com',
            name: 'John',
            rsvp: true,
            status: 'NEEDS-ACTION'
          },
          {
            email: 'mno@gmail.com',
            name: 'Mike Jack',
            rsvp: true,
            status: 'NEEDS-ACTION'
          },
          {
            email: 'xyz@gmail.com',
            name: 'Will Paul',
            rsvp: true,
            status: 'NEEDS-ACTION'
          }
        ]
      }
    ]
  }).toString();

```

calling with `Nodemailer`

```
message: {
      to: toEmail,
      headers: {
        'x-invite': {
          prepared: true,
          value: id
        }
      },
      alternatives: [
        {
          contentDisposition: 'attachment',
          filename: 'meeting.ics',
          contentTransferEncoding: '7bit',
          contentType: 'text/calendar; charset="utf-8"; method=PUBLISH',
          content: content
        }
      ]
    },
```

I have added attendees but it is not showing up in the calendar (Google, Apple).

**Comment by souravpakhira2** [comment]
> I'm getting the same issue - not adding automatically to the calendar. My code looks like this.
> 
> ```
> const content = ical({
>     domain: 'google.com',
>     prodId: '//Google Inc//Google Calendar 70.9054//EN',
>     timezone: 'Australia/Brisbane',
>     method: 'PUBLISH', //REQUEST
>     scale: 'GREGORIAN',
>     events: [
>       {
>         start: moment(),
>         status: 'CONFIRMED',
>         end: moment().add(1, 'hour'),
>         summary: 'Calendar invite test',
>         organizer: {
>           name: 'Shashank Kumar',
>           email: 'xyz@gmail.com',
>           mailto: 'xyz@gmail.com'
>         },
>         location: 'Zoom',
>         attendees: [
>           {
>             email: 'abc@gmail.com',
>             name: 'John',
>             rsvp: true,
>             status: 'NEEDS-ACTION'
>           },
>           {
>             email: 'mno@gmail.com',
>             name: 'Mike Jack',
>             rsvp: true,
>             status: 'NEEDS-ACTION'
>           },
>           {
>             email: 'xyz@gmail.com',
>             name: 'Will Paul',
>             rsvp: true,
>             status: 'NEEDS-ACTION'
>           }
>         ]
>       }
>     ]
>   }).toString();
> ```
> 
> calling with `Nodemailer`
> 
> ```
> message: {
>       to: toEmail,
>       headers: {
>         'x-invite': {
>           prepared: true,
>           value: id
>         }
>       },
>       alternatives: [
>         {
>           contentDisposition: 'attachment',
>           filename: 'meeting.ics',
>           contentTransferEncoding: '7bit',
>           contentType: 'text/calendar; charset="utf-8"; method=PUBLISH',
>           content: content
>         }
>       ]
>     },
> ```
> 
> I have added attendees but it is not showing up in the calendar (Google, Apple).

were able to add the calendar invite? Because im also stuck with the same issue
