### ISSUE TITLE
Email sent issue with list of Attendies

### ISSUE THREAD

**Issue by Andlibmehndi** [sebbo2002/ical-generator#179]
Hi @sebbo2002 ,
I have used Nodemail to send calendar events and used your "ical-generator" but when i am adding list of all attendees then it is displaying in the message but email is not sent to any of the attendees.

Could you please help me with this? @sebbo2002 
I have use Node and Nodemailer for sending emails.

```
 const cal = ical({ domain: 'xxxxxxxx' });
    const unixtodate = moment.unix(ICSobj.date).format("MM/DD/YYYY");
    var timeObj = await convertTime(ICSobj.NS, ICSobj.NE);
    const startUnix = await moment(`${unixtodate} ${timeObj.NSHours}:${timeObj.NSMin}`, "MM/DD/YYYY HH:mm").unix();
    const endUnix = await moment(`${unixtodate} ${timeObj.NEHours}:${timeObj.NEMin}`, "MM/DD/YYYY HH:mm").unix();
    cal.domain('mail.thegatewaycorp.com');
    cal.method('ADD');

    const event = await cal.createEvent({
        start: moment.unix(startUnix).toISOString(),
        end: moment.unix(endUnix).toISOString(),
        summary: 'Conference Room Meeting 10',
        location: `${ICSobj.location}`,
        description: `Hi, Your are invited by ${ICSobj.personalinfo.name} to attend Meeting. 
        The Meeting would start ${moment.unix(ICSobj.date).format("MM/DD/YYYY")} FROM ${timeObj.NSHours}:${timeObj.NSMin}
        To ${timeObj.NEHours}:${timeObj.NEMin}.`,
        //organizer: `Organizer\'s ${ICSobj.personalinfo.name} <${ICSobj.email}>`,
        organizer: `Organizer\'s Madhav <${ICSobj.email}>`
    });
    event.location(`${ICSobj.location}`);
    await event.attendees(attendies);
    let data = await cal.toString();
```

Nodemailer Code

 [ let transporter = nodemailer.createTransport({
        host: emailConfig.smtp,
        port: emailConfig.port,
        secure: false, // true for 465, false for other ports
        auth: {
            user: emailConfig.userName,
            pass: emailConfig.password
        },
        tls: {
            rejectUnauthorized: false
        }
    });

    // send mail with defined transport object
    let info = await transporter.sendMail({
        from: `Conference Room ${emailConfig.from}`, // sender address
        to: sentObj.Organizer, // list of receivers {emailAddress}
        cc:sentObj.cc,
        subject: 'Conference Appointment', // Subject line,
        text: "Conference Appointment Invitation",
        icalEvent: {
            filename: 'invitation.ics',
            content: icsString
        }
    });

    console.log('Message sent: %s', info.messageId);
    return info.messageId;](url)

**Comment by sebbo2002** [comment]
`ical-generator` only generates iCal files, but does not send invitations. If you want to send invitations to your attendees, you have to do it manually. Please reopen the issue if you have further questions regarding this library.
