### ISSUE TITLE
No newline for X- attributes?

### ISSUE THREAD

**Issue by vicky-blr** [sebbo2002/ical-generator#180]
I'm trying to add custom attributes but it looks like it doesn't add `\r\n` at the end as it adds for other attributes. [Here](https://github.com/sebbo2002/ical-generator/blob/develop/src/_tools.js#L142) it joins with `\r\n` but if there is only one attribute, it won't add `\r\n` at the end? When I look at source code of email I get, it's not adding newline which is an issue at the moment, correct me if I'm missing something ?

**Comment by sebbo2002** [comment]
You're absolutely right, of course. I will try to solve that in the next few days. Thank you for your hint.

**Comment by vicky-blr** [comment]
I think easiest change would be to change [this line](https://github.com/sebbo2002/ical-generator/blob/a436b85962d1ce7d69bdcd25cfc2ae75c864cc0f/src/event.js#L1139) to add `\r\n`.

Old:   `g += ICalTools.generateCustomAttributes(this);`
New: `g += ICalTools.generateCustomAttributes(this) + '\r\n';`

**Comment by sebbo2002** [comment]
I know, thank you, but I don't have the time right now. Hope to find a minute this evening, otherwise it woun't happen before sunday. Sorry.
