### ISSUE TITLE
Unable to open `.ics` file on iOS Calendar

### ISSUE THREAD

**Issue by vchimev** [sebbo2002/ical-generator#182]
Hey there,

I create a `.ics` file on iOS, however, I'm unable to automatically open it on the default iOS Calendar.

Any guidelines?

Sample:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Test//App//EN
NAME:Calendar Event
X-WR-CALNAME:Calendar Event
BEGIN:VEVENT
UID:bk0m@ORGANIZER
SEQUENCE:0
DTSTAMP:20200213T094456Z
DTSTART:20200212T150000Z
DTEND:20200213T150000Z
SUMMARY:Sample summary
ORGANIZER;CN="ORGANIZER":mailto:sample@gmail.com
END:VEVENT
END:VCALENDAR
```

Thank you!

**Comment by sebbo2002** [comment]
Please provide your sample code and detailed instructions on how to transfer the calendar to iOS (Airdrop, HTTP server, etc.) so I can recreate the problem.

**Comment by vchimev** [comment]
Hey @sebbo2002,

Basically, I write a `.ics` file on iOS and try to open it via [UIDocumentInteractionController](https://developer.apple.com/documentation/uikit/uidocumentinteractioncontroller/1616828-presentpreviewanimated?language=objc) without success.

In addition, I manage to open the same `.ics` file on macOS and it automatically adds to the Calendar.

Any hints on how to open it on iOS would be much appreciated.

Thank you!

**Comment by sebbo2002** [comment]
If I save your example as an ics file and send it to an iPhone via Airdrop, the calendar entry will open just fine. I can also add it to my calendar. So I would rule out at this point that there is a problem with this library or the generated file.

If you have further questions about this library, feel free to reopen the issue.
