### ISSUE TITLE
OOF?

### ISSUE THREAD

**Issue by dargmuesli** [sebbo2002/ical-generator#186]
Hey there, thank you for this great library!

I'm just wondering what the [`busystatus` value `oof`](https://github.com/sebbo2002/ical-generator#busystatusstring-busystatus) means? :D
`free`, `busy` and `tentative` are clear to me. Looking at [the RFC](https://tools.ietf.org/html/rfc5545#section-8.3.6) it must be `BUSY-UNAVAILABLE`? But why is it called `oof`?

Have a good day :)

**Comment by sebbo2002** [comment]
The method busystatus() currently only implements 'X-MICROSOFT-CDO-BUSYSTATUS', not the RFC. Documentation can be found [here](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcical/cd68eae7-ed65-4dd3-8ea7-ad585c76c736). I'll leave this issue open to fix this, it's not very nice to have this up to date, I understand that.
