### ISSUE TITLE
Type issue - OPT_PARTICIPANT should be OPT-PARTICIPANT.

### ISSUE THREAD

**Issue by IainAdams** [sebbo2002/ical-generator#192]
Hi,

When I attempt to use 'OPT_PARTICIPANT' I get an error: "Error: `role` must be one of the following: CHAIR, REQ-PARTICIPANT, OPT-PARTICIPANT, NON-PARTICIPANT!"

However, OPT_PARTICIPANT is set in the types.

type attendeeRole = 'CHAIR' | 'REQ-PARTICIPANT' | 'OPT_PARTICIPANT' | 'NON-PARTICIPANT';

Thakns
Iain

**Comment by gprst** [comment]
The bug seems to be fixed, this issue can be closed 🙂

**Comment by sebbo2002** [comment]
Just released v1.15.1 with a bug fix. Thanks for reporting it.
