### ISSUE TITLE
UID Entropy very low

### ISSUE THREAD

**Issue by janrg** [sebbo2002/ical-generator#200]
Currently, if no ID is given to the event manually, a 4 character ID is generated consisting of the character set a-z 0-9. This has an entropy of less than 21 bits and creating more than a few tens of events in a calendar comes with a significant risk of id collisions. I would suggest either modifying the current method to create significantly longer random strings or switching to UUIDs (which is the official recommendation, see https://icalendar.org/New-Properties-for-iCalendar-RFC-7986/5-3-uid-property.html).
 In the latter case, fully following the recommendation would also mean getting rid of the domain property, though it would still be valid to include it after the UUID, provided the domain name is no longer than 218 bytes. It should be noted though that the spec states ```"UID" values MUST NOT include any data that might identify a user, host, domain, or any other security- or privacy-sensitive information.``` 

Either way, if you would like such a change and let me know which variant you prefer, I'd be happy to create a PR.

**Comment by sebbo2002** [comment]
I have been planning to use UUIDs for some time, but then I would also throw away domain(). Accordingly, I'm planning to make the change for a new version when a little bit of stuff has come together. You are welcome to create an issue, I don't think there is one yet.

But as a quick fix I would prefer the longer IDs. Enough for now and we can clean it later.

**Comment by janrg** [comment]
Alright, I'll create a PR for longer IDs.
