### ISSUE TITLE
Typescript: EventData.x should be optionnal

### ISSUE THREAD

**Issue by TruffeCendree** [sebbo2002/ical-generator#212]
Commit https://github.com/sebbo2002/ical-generator/commit/ae52dae21e31ff0ab652599b46e4c900721daf32 added the support of 'x' attributes on EventData in index.d.ts:

I suggest to added a '?' to notify that this attribute is optional.

``` typescript
x?: { key:string, value:string }[];
```

For the moment, my typescript does not compile anymore without adding the x attribute to `cal.createEvent()`.

**Comment by karlhorky** [comment]
Pull request for this open at #211.

**Comment by sebbo2002** [comment]
Closing as pull request got merged, thank you all
