### ISSUE TITLE
Add support for `WKST`

### ISSUE THREAD

**Issue by sharathprabhal** [sebbo2002/ical-generator#213]
Request: Add support for `WKST`, option to specify start of week, as per https://icalendar.org/iCalendar-RFC-5545/3-3-10-recurrence-rule.html

Thanks!

**Comment by sharathprabhal** [comment]
@sebbo2002 would you accept a PR for this?

**Comment by sebbo2002** [comment]
@sharathprabhal I would accept a PR if the feature is complete, i.e. there are unit tests in addition to the implementation and the documentation / readme has been updated. Otherwise I would leave the PR here with todo label until I find more time for this project.

**Comment by sebbo2002** [comment]
Didn't have a laptop with me this weekend, I'll look at it tonight. Thanks in advance ☺️
