### ISSUE TITLE
Line folding breaks surrogate pairs

### ISSUE THREAD

**Issue by HeikoTheissen** [sebbo2002/ical-generator#221]
https://github.com/sebbo2002/ical-generator/blob/d4cd9cd44a378113b194bc8a8147cea9fdc6a50d/src/_tools.js#L93

Folding an iCalendar line after every 74 characters does not work if the 74th and 75th character form a [surrogate pair](https://mathiasbynens.be/notes/javascript-encoding#surrogate-pairs). iCalendar clients are unable to reconstitute the pair if it is split across two lines.

For example,
```js
'use strict';

const ical = require('ical-generator');
const moment = require('moment');
const cal = ical({domain: 'localhost'});

// overwrite domain
cal.domain('example.com');

const event = cal.createEvent({
    start: moment().add(1, 'hour'),
    end: moment().add(2, 'hours'),
    summary: '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF:📞'
});

console.log(cal.toString());
```
produces output where the telephone symbol is split and rendered by Google Calendar as `...ABCDEF:��`. In such cases, the split must happen *before* the 74th character.

Moreover, even in the absence of surrogate pairs, a line with 74 Unicode characters (which are not all ASCII) can have more than 74 octets and so exceed the limit suggested in the [RFC](https://tools.ietf.org/html/rfc5545#section-3.1).

**Comment by sebbo2002** [comment]
🎉 Released in `1.15.4`, thank you.
