### ISSUE TITLE
Ical is not display content description property in outlook and gmail at same time.

### ISSUE THREAD

**Issue by DipakTechifySolutions** [sebbo2002/ical-generator#222]
I have some trivial issue, Following is the snippet which has created a ical file, When there is a **description** or **htmlDescription** is there it works fine in gmail but it shows html tagged description in outlook in the description box.

But when I use X-ALT-DESC;FMTTYPE=text/html tag specifically resolve an issue for outlook, it does work for outlook but not working for gmail.

So my issue is that any of the one either gmail or outlook working perfectly at a time. When (**description** & **htmlDescription**) and (**X-ALT-DESC;FMTTYPE=text/html**) both are used. 

It does not show content description property in outlook and gmail at same time.

`
const objCalendar = {
      domain: calDomain,
      prodId: { company: propertyName, product: calProductIdName },
      name: calProductName,
      timezone: userTimezone,
    };

    const objEvent = {
      summary,
      description: `Invitation`,
      organizer: { name: organizerName, email: from },
      start: eventStartTime,
      end: eventEndTime,
      location,
    };

    const objCal = await iCal(objCalendar);

    const event = objCal.createEvent(objEvent).x({
      'X-ALT-DESC;FMTTYPE=text/html':`<html><head></head><body>${evDescription}</body></html>`
    });

    // set meeting category
    event.createCategory({ name: calCategory });

    // set meeting attendees
    await attendees.map((attendee) => {
      if (attendee.trim().length > 0) {
        event.createAttendee({
          email: attendee.trim(),
          name: attendee.split('@')[0],
          mailto: attendee.trim(),
        });
      }
      return true;
    });

    // set meeting alaram before 10 minutes
    event.createAlarm({
      type: calAlarmType,
      trigger: 600,
    });

    return transporter.sendMail({
      from,
      to,
      cc,
      bcc,
      subject: summary,
      description,
      icalEvent: {
        filename: calFileName,
        method: calMethod,
        content: objCal.toString(),
      },
    });
  `
  
  I need help for this issue, since 4 days I have tried multiple way but nothing seems working.

**Comment by sebbo2002** [comment]
Please understand that I cannot give support for client- and calendar implementations. I simply do not have the capacity for this. If you want, we can leave the issue open if someone is familiar with the gmail / Outlook implementation.

**Comment by sebbo2002** [comment]
I would close this issue due to inactivity. I hope this is ok for everyone involved. If there is still a need for clarification, please feel free to reopen the issue or create a new ticket if it's a new topic.
