### ISSUE TITLE
Unable to send multiple events

### ISSUE THREAD

**Issue by tar-aldev** [sebbo2002/ical-generator#225]
When following the docs I see that events is an array which makes me think I can put multiple events there.
Like this:

```
const cal = this.icalGenerator({
      domain: 'test.efacity.com',
      name: 'my test calendar event',
      events: [event1, event2, event3, ...]
});
```
When I look at generated calendar string I can clearly see that there are multiple events there. However in the email itself (in gmail) i receive a letter with only first event being displayed. Is it an expected behaviour and is it possible to send multiple events at all?

**Comment by sebbo2002** [comment]
Unfortunately, I cannot give support for iCal clients here. But have a look at Stackoverflow, there are some reports about the horrible iCal support in Gmail, e.g. [this one](https://stackoverflow.com/questions/31141262/add-a-multi-event-icalendar-file-to-google-calendar).
