### ISSUE TITLE
Please add version to package.json

### ISSUE THREAD

**Issue by jkytomak** [sebbo2002/ical-generator#226]
I was interested to try the typescript version of the library, but was not able to use it because there is no version defined in package.json:
```
$ yarn add sebbo2002/ical-generator#feature/2.0
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
error Can't add "ical-generator": invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by sebbo2002** [comment]
Oh that's stupid. Yes, I'll add a placeholder version later. Later, the version will be set automatically by semantic release when the feature branch has been flagged for develop.

**Comment by sebbo2002** [comment]
Added a version and tested it. Should work now. Thanks for reporting it 🥰
