### ISSUE TITLE
What are valid categories?

### ISSUE THREAD

**Issue by gajus** [sebbo2002/ical-generator#232]
I cannot find what are valid values for `CategoryData`.

In the documentation I see values: `MEETING` and `APPOINTMENT`.

Are there any other values?

Where can I find reference for this?

I looked at https://www.kanzaki.com/docs/ical/categories.html, but it does not specify ENUM either.

**Comment by sebbo2002** [comment]
iCal's categories are a [free text field](https://github.com/sebbo2002/ical-generator/blob/develop/src/category.ts#L33), you can choose the categories as you like. So it's similar to tags. `MEETING` and `APPOINTMENT` are just example values.

**Comment by gajus** [comment]
Thank you
