### ISSUE TITLE
CUTYPE

### ISSUE THREAD

**Issue by hryanjones** [sebbo2002/ical-generator#24]
How do you feel about adding in CUTYPE ([reference RFC](https://tools.ietf.org/html/rfc2445#section-4.2.3))? If you like I can try my hand and creating a PR?

**Comment by sebbo2002** [comment]
Merged in [v0.2.3](https://github.com/sebbo2002/ical-generator/releases/tag/0.2.3). Thank you :smile:

**Comment by hryanjones** [comment]
Thanks :)
