### ISSUE TITLE
ability to update existing calendar generated with ical-generator?

### ISSUE THREAD

**Issue by tar-aldev** [sebbo2002/ical-generator#242]
I have a calendar generated with the help of ical-generator.

I could found that the way to update it is to somehow use UID of calendar I want to update. But I cannot find any mention of this in the docs.
Could you please help me with this?

**Comment by sebbo2002** [comment]
Currently, this topic is not in the documentation, as it would go beyond the scope. 

Normally it is sufficient that the events each have a unique ID, which you can specify with `id()` or `uid()`. In addition, you can use `sequence()` to specify which version is the current one. This allows clients to quickly check whether their version is still the current one. You start with `sequence(1)` and each time you change the date, the number is incremented by one.
