### ISSUE TITLE
Make @types/node an optional peer dependency

### ISSUE THREAD

**Issue by adamreisnz** [sebbo2002/ical-generator#244]
Can this be made an optional peer dependency?
We don't use TypeScript and don't want to add bloat to our project by including this as a dependency. 

Everything is working fine _without_ this dependency, so can it be made optional so that we avoid the errors?

`warning " > ical-generator@1.15.4" has unmet peer dependency "@types/node@>= 8.0.0".`

**Comment by sebbo2002** [comment]
Sure, think that also applies for the other peerDependencies, but I have to double check later…

**Comment by adamreisnz** [comment]
Cheers thank you
