### ISSUE TITLE
Ical doesn't add automatically into calendar

### ISSUE THREAD

**Issue by shashankrepo** [sebbo2002/ical-generator#246]
I'm getting the same issue - not adding automatically to the calendar. My code looks like this.

```
const content = ical({
    domain: 'google.com',
    prodId: '//Google Inc//Google Calendar 70.9054//EN',
    timezone: 'Australia/Brisbane',
    method: 'PUBLISH', //REQUEST
    scale: 'GREGORIAN',
    events: [
      {
        start: moment(),
        status: 'CONFIRMED',
        end: moment().add(1, 'hour'),
        summary: 'Calendar invite test',
        organizer: {
          name: 'Shashank Kumar',
          email: 'xyz@gmail.com',
          mailto: 'xyz@gmail.com'
        },
        location: 'Zoom',
        attendees: [
          {
            email: 'abc@gmail.com',
            name: 'John',
            rsvp: true,
            status: 'NEEDS-ACTION'
          },
          {
            email: 'mno@gmail.com',
            name: 'Mike Jack',
            rsvp: true,
            status: 'NEEDS-ACTION'
          },
          {
            email: 'xyz@gmail.com',
            name: 'Will Paul',
            rsvp: true,
            status: 'NEEDS-ACTION'
          }
        ]
      }
    ]
  }).toString();

```

calling with `Nodemailer`

```
message: {
      to: toEmail,
      headers: {
        'x-invite': {
          prepared: true,
          value: id
        }
      },
      alternatives: [
        {
          contentDisposition: 'attachment',
          filename: 'meeting.ics',
          contentTransferEncoding: '7bit',
          contentType: 'text/calendar; charset="utf-8"; method=PUBLISH',
          content: content
        }
      ]
    },
```

I have added attendees but it is not showing up in the calendar (Google, Apple).

**Comment by sebbo2002** [comment]
Please understand that I cannot give support for client- and calendar implementations. I simply do not have the capacity for this. If you see a bug in ical-generator or invalid results are produced by it, you are of course welcome to contact me again. 

I would leave the issue open here, maybe someone else has already solved the problem and is kind enough to help...

**Comment by samuelfruhauf** [comment]
I'm facing the same problem, have a solution?

**Comment by Gr8z** [comment]
After the major update, I also don't see any events being added to my outlook calendar. This was something working before in v1, but now renders the event file useless when opened in outlook.

**Comment by sebbo2002** [comment]
@Gr8z Can you play back the code and generate an iCal file? Then you could compare what has changed between v1 and v2 and possibly recreate the problem.

Unfortunately, I don't have Outlook, so I can't test it on my computer.

**Comment by Gr8z** [comment]
I apologize for the my stupidity but the reason why the event was not showing up on my Outlook calendar is because I was creating one in 2020 instead of 2021. Took me several days to figure this out. 

Other than that, v2 is working great.
