### ISSUE TITLE
`SOURCE;VALUE=URI` param not supported

### ISSUE THREAD

**Issue by irfaan** [sebbo2002/ical-generator#260]
Hi! Wondering if `SOURCE;VALUE=URI` is supported in some way. According to the spec ([5.8. SOURCE Property](https://icalendar.org/New-Properties-for-iCalendar-RFC-7986/5-8-source-property.html)), it looks like this is how the client knows where to refresh calendar data.

Is this perhaps supported in some alternative way? I'm using `METHOD:PUBLISH` and adding the calendar via `webcal://` call to the `.ics` file.

**Comment by sebbo2002** [comment]
Currently `SOURCE` is not implemented, only url to provide an alternative.
