### ISSUE TITLE
Missing implementation of refresh-interval

### ISSUE THREAD

**Issue by paulwer** [sebbo2002/ical-generator#273]
Look at: https://icalendar.org/New-Properties-for-iCalendar-RFC-7986/5-7-refresh-interval-property.html
Ist it possible to implement this feature? Or do i missed it?

**Comment by sebbo2002** [comment]
> Or do i missed it?

No, the attribute is not currently implemented.

**Comment by paulwer** [comment]
I take a look to the code and found the option ttl (time to live), which sets the requested line. Sorry i'am not that fit to typescript.
But maybe it should be a good option to mark this option in the docs for other people.

ex. /src/calendar.ts line 840

**Comment by sebbo2002** [comment]
Okay, you shouldn't trust the mobile GitHub search 😂.

It already says "Is used to fill `REFRESH-INTERVAL` and `X-PUBLISHED-TTL` in your iCal." What else is missing for you?

**Comment by paulwer** [comment]
its fine for me now. thank for your responses.
