### ISSUE TITLE
UID contain start date

### ISSUE THREAD

**Issue by kkozlik** [sebbo2002/ical-generator#28]
What is the reason the UID in generated ical contain the start date?

g += 'UID:' + __tools.formatDate(data.start)__ + '-' + data.id + '@' + calendar.domain() + '\r\n';

With this it is not possible to update existing events. The updates have to have same UID. And even if I set the same uid using uid() function, the UID in generated file differs.

**Comment by sebbo2002** [comment]
To be honest: I have no idea… 🙈
I fix this tomorrow morning, thank you.
