### ISSUE TITLE
I am updating created event but it is not reflecting in google calendar and showing this event is out of date , but same is working for outlook 

### ISSUE THREAD

**Issue by abhishek-kesharwani** [sebbo2002/ical-generator#298]
Can anyone plz help me?

**Comment by sebbo2002** [comment]
Please understand that I cannot give support for client- and calendar implementations. I simply do not have the capacity for this. If you see a bug in ical-generator or invalid results are produced by it, you are of course welcome to contact me again.

I would leave the issue open here, maybe someone else has already solved the problem and is kind enough to help...

**Comment by AndrewLane** [comment]
@abhishek-kesharwani In my experience, there's a significant lag with Google Calendar in terms of how long it will take for updates to be synchronized.  It's quite annoying.  If I recall, it was around 13 hours or so with my experiments.  Are you seeing something like that?

**Comment by abhishek-kesharwani** [comment]
Thanks @AndrewLane I understood this but as you said it is around 13 hours so it means the code that I am using should not work locally but when I run this code locally in that case Gmail calendar is reflecting updated time and date properly and problem occurs when I deploy this code in cloud.

**Comment by AndrewLane** [comment]
Hmm, I'm not sure I fully understand exactly what's going on.  Anyway you can expound on exactly what you are doing?

**Comment by abhishek-kesharwani** [comment]
Ok See. I created meeting using NodeMailer and try to update same meeting which is perfectly working on outlook and also in Gmail calendar. but when I deploy this code in aws in that case create meeting is working properly but in update meeting ,
outlook calendar is reflecting correct time and date but in gmail calendar I am getting this **This invitation is out of date. This event has been updated.**. but this should be reflect in original created meeting 
![gmail](https://user-images.githubusercontent.com/47901187/124593161-efc5e680-de7b-11eb-97e9-50cc8a904de2.png)

**Comment by AndrewLane** [comment]
> Ok See. I created meeting using NodeMailer and try to update same meeting which is perfectly working on outlook and also in Gmail calendar locally. but when I deploy this code in aws in that case create meeting is working properly but in update meeting
> ,outlook calendar is reflecting correct time and date but in gmail calendar I am getting this **This invitation is out of date. This event has been updated.**. but this should be reflect in original created meeting
> ![gmail](https://user-images.githubusercontent.com/47901187/124593161-efc5e680-de7b-11eb-97e9-50cc8a904de2.png)

Thank you.  Unfortunately I am out of my depth here so I cannot try to help further.  Good luck!

**Comment by abhishek-kesharwani** [comment]
> > Ok See. I created meeting using NodeMailer and try to update same meeting which is perfectly working on outlook and also in Gmail calendar locally. but when I deploy this code in aws in that case create meeting is working properly but in update meeting
> > ,outlook calendar is reflecting correct time and date but in gmail calendar I am getting this **This invitation is out of date. This event has been updated.**. but this should be reflect in original created meeting
> > ![gmail](https://user-images.githubusercontent.com/47901187/124593161-efc5e680-de7b-11eb-97e9-50cc8a904de2.png)
> 
> Thank you. Unfortunately I am out of my depth here so I cannot try to help further. Good luck!
Thanks @AndrewLane  
Plz help me once 
If updated Event is not showing in google calendar but it is working properly in outlook then in that case what we can do. can we perform any changes ?

**Comment by huksley** [comment]
answered in #273 

```calendar.ttl(60)```

**Comment by sebbo2002** [comment]
@abhishek-kesharwani Could your problem be solved with @huksley's answer?
