### ISSUE TITLE
Making peer dependencies less strict

### ISSUE THREAD

**Issue by thetutlage** [sebbo2002/ical-generator#303]
The `peerDependencies` defined in the package.json file https://github.com/sebbo2002/ical-generator/blob/develop/package.json#L68-L70 are a little more strict than they really have to be.

For example: I cannot use ical-generator with types from Node16 as the range defined is `^15.0.3`. Same is true with `luxon`.

Shouldn't we change them to accept anything greater than the supported version `>= 15.0.3`?

---

I am using npm version `7.19.1`

**Comment by sebbo2002** [comment]
You are absolutely right. I hope to find time to do it this week, I hope it's not time-critical.

**Comment by thetutlage** [comment]
Thanks :)
