### ISSUE TITLE
Location formatting

### ISSUE THREAD

**Issue by AlexHorstkoetter** [sebbo2002/ical-generator#314]
When specifying a location with a title, address, geolocation and radius the location attribute is emitted as "title" + "address".
But when specifying a location with just a title and an address, only the title is emitted and the address is swallowed.
I would have to manually concatenate title and address and pass them into title, which is not very intuitive and not documented anywhere. Is this intended behavior?
I get that all 4 parameters are needed to emit X-APPLE-STRUCTURED-LOCATION, but why would geolocation affect regular address formatting?

**Comment by sebbo2002** [comment]
I am currently on holiday and do not have a laptop with me. Therefore, I will only be able to help after my vacation, as I would also have to do some research. I hope you can wait. Thank you
