### ISSUE TITLE
Disable automagic `setZone`

### ISSUE THREAD

**Issue by adamreisnz** [sebbo2002/ical-generator#320]
Hi, first of all thank you for a great library. 

We pass in either moment or Luxon DateTime objects into ical-generator, but we already set the correct timezone on these objects manually.

Is it possible to disable the behaviour as documented here:

![image](https://user-images.githubusercontent.com/490562/135773994-f955d165-6604-4341-94b9-694f8bb1e0b0.png)

E.g. disable the `setZone` based on timezone of the calendar/event, and simply let us be in control of setting the correct zones?

I don't like 3rd party libraries modifying our input which can lead to unexpected behaviour. It should be the user's responsibility to set the correct timezone on the date inputs provided.

**Comment by sebbo2002** [comment]
> Is it possible to disable the behaviour as documented here:
> 
> E.g. disable the setZone based on timezone of the calendar/event, and simply let us be in control of setting the correct zones?

Currently, this is not planned. 

> I don't like 3rd party libraries modifying our input which can lead to unexpected behaviour. It should be the user's responsibility to set the correct timezone on the date inputs provided.

Ideally, the change should make no difference because the time zone is already correct anyway. Unfortunately, a lot of questions arise here if the library doesn't automatically take care of this, so I decided to take this step, even though I personally don't find it nice. Moment objects are cloned before the time zone is set, so the original is never changed.

We can of course talk about a way to deactivate this conversion. Do you currently have any disadvantages or problems with this implementation? Or are you only interested in eliminating this possible error case?

**Comment by adamreisnz** [comment]
Ok, I understand.

Well, I just find it rather confusing to figure out what will happen, and what we need to do on our end.
Basically, there are now 3 ways of passing the timezone:

* Set it on the moment/luxon object that you pass into the library
* Set it when creating an event
* Set it when creating the calendar

The problem is that I don't think this is properly documented and a lot of "magic" seems to happen under the hood.

For example:
* Why do we have to pass in timezone to the calendar and to events separately?
* What happens if we pass different timezones to the calendar and to the event? Which one takes priority?
* What if we pass a moment object with a set timezone and pass a different one to the calendar? Will the moment object timezone be overwritten?
* What happens if we pass a moment object with timezone and don't pass timezone information into the calendar and event? Is this ok? Will this work as expected?

Would be good to have that clarified and/or simplified a bit, but I understand that people that "just want it to work" may not get it.

**Comment by sebbo2002** [comment]
> Set it on the moment/luxon object that you pass into the library

However, ical-generator is currently not aware of this. Yes, you can do that, but it should not be written anywhere in the documentation. After all, ical-generator can also handle normal date objects or moment (without moment-timezone). So you can't rely on timezone information on the incoming date object. Unfortunately.


> Set it when creating an event

Perfect. Then the time zone only applies to this one event.


> Set it when creating the calendar

Also good. This time zone then applies to every event, unless the event is given its own time zone. The time zone of the calendar is therefore the fallback if the event has no time zone defined.


> Why do we have to pass in timezone to the calendar and to events separately?

You don't have to, these are simply two ways of doing it. It's currently very poorly documented, that's what I'm noticing.


> What happens if we pass different timezones to the calendar and to the event? Which one takes priority?

If both time zones are set, the time zone of the event wins. The calendar time zone is only used if the event has no time zone.


> What if we pass a moment object with a set timezone and pass a different one to the calendar? Will the moment object timezone be overwritten?

Yes, the time zone is set via ical-generator's `timezone()` method. For the simple reason that this works for all input formats (Date, String, Moment, Moment-Timezone, Luxon, DayJS).


> What happens if we pass a moment object with timezone and don't pass timezone information into the calendar and event? Is this ok? Will this work as expected?

Probably not. The time zone is not fetched from the moment-timezone object, so the information about the time zone in the calendar will be missing.


> Would be good to have that clarified and/or simplified a bit, but I understand that people that "just want it to work" may not get it.

I will definitely add what I have written here to the documentation, I hope that makes it a little better. Until then, I'll leave the ticket open here.

Unfortunately, I don't currently have any ideas on how I could simplify the whole thing. If you have any ideas, please let me know.

**Comment by adamreisnz** [comment]
Ok thanks for clarifying that. I think with this guidance in mind it becomes fairly straightforward. Since we only use a single ical instance to generate one invite per email, I'll probably stick to passing it per event and ignore passing it to the calendar. In combination with passing in luxon objects, this should work as I want it to.

I did note an issue yesterday, and I am not sure if this is a bug in ical or if we were doing something wrong.

But we were passing in plain date objects by accident (not converted to Luxon first), which came straight out of the mongoDB database and would have been a Date object in UTC time.

We were also setting the timezone in the calendar object.

However, the resulting calendar invite, had the start and end times in the incorrect (local) timezone.

This was fixed by passing in a Luxon DateTime object and also setting the timezone on the event.

Not sure if that's expected, but I would have thought passing in plain date objects should also work and respect the passed in timezone.

Thanks for adding the above to the documentation.

**Comment by sebbo2002** [comment]
> Not sure if that's expected, but I would have thought passing in plain date objects should also work and respect the passed in timezone.

That should definitely work. [Here](https://github.com/sebbo2002/ical-generator/blob/develop/test/cases.ts#L99) is an example in the tests, the result looks like [this](https://github.com/sebbo2002/ical-generator/blob/develop/test/results/generate_04.ics#L38).

If you have a small code example where it doesn't work like this, I would be very happy about it so I can add it to the tests. That would definitely be a bug then.

**Comment by adamreisnz** [comment]
Ok I'll see if I can replicate it in isolation
