### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by Pflyg** [sebbo2002/ical-generator#325]
When I try to use the toString method in browser (webpack), I get the following Error
```
Uncaught ReferenceError: Buffer is not defined
    foldLines tools.js:109
    foldLines tools.js:100
    toString calendar.js:411
    toBlob calendar.js:280
    ts ICal.ts:19
 ```

Same with toURL and toBlob

**Comment by sebbo2002** [comment]
Oh crap. Sorry, currently `ical-generator` is not usable in the browser. The reason is [this line](https://github.com/sebbo2002/ical-generator/blob/fba27406775164a1c2dfad0f703b2a3b207f445c/src/tools.ts#L139), which currently does not work in the browser. I will provide a fix as soon as I get to it.
