### ISSUE TITLE
Setting timezone as UTC creates strange behaviour

### ISSUE THREAD

**Issue by pezza3434** [sebbo2002/ical-generator#328]
Hi there,

Thanks for a maintaining this great package, I've been using it for a few years. I've just upgraded to the latest version from 1.4.3.

Just a heads up, that setting the timezone to utc:

`const cal = ical({
        domain: "eventcalendarapp.com",
        name: calendarName,
        timezone: "UTC",
        method: "publish"
    });`

Stops the DTStart and DTEnd dates from being created with a 'Z' at the end. Which if I understand correctly makes them floating times. 

Removing the timezone solves the issue, and reading the readme and the code it seems if no timezone is stated then it is handled in UTC time. Just a bit strange behaviour.

Apologies for being lazy and not doing a pull request.

Thanks again for a great package.

**Comment by pezza3434** [comment]
Related to this, if you set UTC as a timezone for an event, the dates become 'TZID=UTC 2021blahblah'. I'm not sure if setting the TZID on an event to utc is ever valid based on this from the spec:

"This parameter MUST be specified on the "DTSTART",
      "DTEND", "DUE", "EXDATE", and "RDATE" properties when either a
      DATE-TIME or TIME value type is specified and when the value is
      neither a UTC or a "floating" time."

I could be wrong, I haven't researched the issue in huge detail.

**Comment by sebbo2002** [comment]
> Removing the timezone solves the issue, and reading the readme and the code it seems if no timezone is stated then it is handled in UTC time. Just a bit strange behaviour.

Currently UTC is the default and therefore does not need a call to `timezone()`. The call with `timezone('UTC')` currently causes incorrect output, I would now note this here as a bug. The correct call for UTC would be `timezone(null)` or no call at all.
