### ISSUE TITLE
Support for attachment property

### ISSUE THREAD

**Issue by Timebutt** [sebbo2002/ical-generator#335]
Hi! I noticed the current `ICalEvent` and `ICalEventData` don't support the `ATTACH` property when creating an event through `createEvent`, [as defined in the spec](https://www.kanzaki.com/docs/ical/attach.html).

Are there any plans to add support, or should we get an implementation running using the last property of `ICalEventData`?

```
x?: {
        key: string;
        value: string;
    }[] | [string, string][] | Record<string, string>;
```

Thanks!

**Comment by sebbo2002** [comment]
So far there has been no demand for it and therefore no plans to implement it. Definitely makes sense though and I would look into it when I get the time. Honestly though, I have to say that this probably won't be the case until early next year. 

If this is too long for you, feel free to use `x()` or you can prepare a pull request.

**Comment by Timebutt** [comment]
Thanks for your reply ;) I'll have a look at how I'll set it up, and might propose a PR to implement this feature!

**Comment by sebbo2002** [comment]
If you have any questions, feel free to contact me here. I will try to answer them in a timely manner.

**Comment by Timebutt** [comment]
Hey @sebbo2002, I see you added support for `attachments`, great! I was just wondering, is the `url` the only property you need for this to work? I actually started implementing this myself a little while back, and did things a bit differently. [This](https://github.com/Timebutt/ical-generator/tree/add-support-for-attachments) is my branch and implementation. It has support for the `fileName`, on top of the `url`.

I haven't reported back yet, because I couldn't get it to work with `iCal` or `Google Calendar` (attachments wouldn't show up, maybe I got something wrong), did you experience the same issues? I'll give your new code a go and see where it differs!

**Comment by sebbo2002** [comment]
I stuck with the spec and tested it with Apple's Calendar. Has worked flawlessly. Google Calendar I have not tested because I do not use that, but I assume that they stick to the spec or not?

<img width="343" alt="Bildschirmfoto 2022-01-03 um 19 40 55" src="https://user-images.githubusercontent.com/812398/147967269-3d1c439d-da45-4944-9140-0fe358a39486.png">

**Comment by Timebutt** [comment]
AFAIK they do yes, looks like I made a mistake on my end then, will have a look and see if anything might need changes for Google Calendar 👌

**Comment by sebbo2002** [comment]
Sounds good. Then I wait with the release (#339) until you have tested it with Google Calendar and given the okay.

**Comment by Timebutt** [comment]
K just tested this, and I see it works when directly importing the `.ics` file (as did my solution). It doesn't work for me, when I fetch it from a remote location through a subscription, which is what my application aims to achieve. Will dig in a bit deeper if I can make it work that way, but basically the functionality is correct 👌

**Comment by sebbo2002** [comment]
Oh wow. And with filename it works? Thanks for your research.

**Comment by Timebutt** [comment]
No, the presence of a file name or even the `FMTTYPE` property makes no difference from what I've found so far :/

**Comment by sebbo2002** [comment]
Maybe the embedding of files directly works? I thought I leave that out, because the feeds are really unattractive large, but if it does not work otherwise we should adjust that again.

**Comment by Timebutt** [comment]
Might work, although I can imagine they'll strip that as well, on top of the the very undesirable fact that the calendar file might become huge as well :/

**Comment by Timebutt** [comment]
Not yet, haven't been able to investigate more because of other work. I honestly don't think that it's related to the implementation of this package, rather in the way that both Google Calendar as well as iCal treat calendar subscriptions, feels like they might be sanitizing attachments for security reasons. I'll see if I get some more time in the near future to investigate, but meanwhile I'd argue this issue is done, as the implementation works great when importing generated `.ics` files!

**Comment by sebbo2002** [comment]
That makes sense. Then I'll mark this ticket as closed, then I can publish this within the next few days together with #340. If you find out anything in your investigation, feel free to let me know.
