### ISSUE TITLE
Attendee RSVP is not honoured when value is false

### ISSUE THREAD

**Issue by samberic** [sebbo2002/ical-generator#340]
Apologies for not raising this as a PR fix- I'll try and find time this week if you can't get their first.

For attendee if it's set to false then it isn't represented in the iCal object.  This is due to the code at https://github.com/sebbo2002/ical-generator/blob/develop/src/attendee.ts#L548-L550

`   if (this.data.rsvp) {
            g += ';RSVP=' + this.data.rsvp.toString().toUpperCase();
        }`

Because the value is false, it doesn't enter this if loop.  Instead this needs to check if the key is present and, presumably, that it's a boolean, and if so fall in and append the RSVP.

**Comment by sebbo2002** [comment]
I can possibly take care of it tonight, thank you.
