### ISSUE TITLE
Documentation website does not work

### ISSUE THREAD

**Issue by Loskir** [sebbo2002/ical-generator#343]
https://sebbo2002.github.io/ical-generator returns 404

**Comment by sebbo2002** [comment]
There is no documentation on this page, it is on https://sebbo2002.github.io/ical-generator/develop/reference/. This is also correctly linked in the readme as far as I can see. Where did you get this link?

**Comment by sebbo2002** [comment]
I have adjusted the corresponding urls in the code, with the new version the problem should be fixed then.

**Comment by sebbo2002** [comment]
And: Thank you for reporting. ❤️
