### ISSUE TITLE
Reapting weekly not working correctly

### ISSUE THREAD

**Issue by ynynl** [sebbo2002/ical-generator#349]
I have created a calendar event that last for two days, and I want to the event to repeat weekly. Here is my code:

```javascript
        const calendar = ical({ name: 'two day window' });
        calendar.createEvent({
            start: moment(:"2022-01-30 00:00:00"),
            end: moment("2022-01-31 23:59:00"),
            summary: '',
            description: '',
        })
            .repeating({
                freq: 'WEEKLY',
            });
```
Jan 30th and Jan 31st is Sunday and Monday. So basically I want the events take place every week from Sunday to Monday. 

But what happened is that the calendar that created only work correctly until March 13th. Starting March 13th, the events start on Monday and end on Tuesday, which is one day longer than expected. 

How can I fix it? 

Thank you!

**Comment by sebbo2002** [comment]
I guess that in your time zone the clock will be changed on March 13? You are currently creating a calendar with UTC time zone, which means as soon as the clock is changed, this is no longer correct. 

You can now either specify the appropriate time zone that should be applied to your calendar (see also [the note on time zones in the readme](https://github.com/sebbo2002/ical-generator#-date-time--timezones)) or you define the event as a [floating event](https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#floating) - with that the specified time applies regardless of the user's time zone (an event from 2-4 o'clock would then always be from 2-4 o'clock in each time zone).

I hope this helps you. Feel free to open the ticket again if you have further questions.
