### ISSUE TITLE
Problem in start/end/timestamp creation

### ISSUE THREAD

**Issue by eajimmy** [sebbo2002/ical-generator#35]
Hi all, 
I've found a problem in event.js part, where there is the date control: 
(!(start instanceof Date) || !start.getTime())
it fails in case of the date 01/01/1970 00:00:00, because getTime() returns 0 that is false, even though the date is valid. It's possible to change it with a clever control or just checking only the instanceof?

Many Thanks,
eajimmy

**Comment by sebbo2002** [comment]
Yep, that was kind of stupid, sorry for that. I'll replace that soon…

```javascript
if(!(start instanceof Date) || isNaN(start.getTime())) {
    throw '`start` must be a Date Object!';
}
```
