### ISSUE TITLE
Sync calendars

### ISSUE THREAD

**Issue by KrisLau** [sebbo2002/ical-generator#359]
So I'm working on a react native app with a NodeJS backend that has a calendar with possibly recurring events. I'm storing the events, individual event occurrences, and attendees in my DB. I'm trying to figure out how to allow users to sync their calendars with Google calendars, outlook, apple calendars, etc using a link. 

From my understanding that would require me to create an ICS file with a public URL that the calendar apps can read. I looked through this package but I'm kind of confused how I would go about doing that since it doesn't seem like I can edit an existing ics file in the case that a user adds more events/updates an existing one? Or is there another way that you guys are doing it like recreating the entire ICS file at intervals using a script of some sort?

**Comment by sebbo2002** [comment]
ical-generator is normally used in a way that all data like events, etc. are already available in a database or similar and then ical files are created either on-demand (e.g. with [serve](https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalCalendar.html#serve)) or periodically (e.g. with [save](https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalCalendar.html#save)). That means you create a new ical file every time you make a change. 

Does that already answer your question? If not, feel free to open the ticket again and specify your question. Thank you very much.

**Comment by KrisLau** [comment]
@FabianMeul The client calendar feed automatically hits the endpoint you give it to sync at intervals that differ based on the application. At least that is my understanding of it based on other sites that implement similar features. This one is the clearest answer I've seen so far:
https://www.addevent.com/help/article/52/how-often-do-my-calendar-events-update-in-subscribers-calendars
