### ISSUE TITLE
Timezones are always in East Coast format

### ISSUE THREAD

**Issue by bostondevin** [sebbo2002/ical-generator#36]
What is the correct format for the timezone name? Using "America/Boise" which i'm getting from moment.js I should be in that timezone, but when I open this in outlook, it's in East Coast timezone:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
NAME:Demo Calendar
X-WR-CALNAME:Demo Calendar
TIMEZONE-ID:America/Boise
X-WR-TIMEZONE:America/Boise
BEGIN:VEVENT
UID:ysc6@http://localhost
SEQUENCE:0
DTSTAMP:20151218T234217Z
DTSTART:20151216T210007Z
DTEND:20151216T220007Z
SUMMARY:Awesome New Event
DESCRIPTION:ABC Company
URL;VALUE=URI:http://localhost:9999/launcher/5671db2cbeaaef790379dbe5
END:VEVENT
END:VCALENDAR

**Comment by takkaria** [comment]
If you want to mark the event as being in the 'America/Boise' timezone, then you need to set the timezone on the event as that as well as the one in the calendar (and make sure that the start and end times you're providing are in local time).

**Comment by sebbo2002** [comment]
Unfortunately some clients don't handle UTC timestamps as my calendar app does.

As @takkaria pointed out, you need to set the timestamp on each event as well. This will get changed in a future version, so the event's timezone inherits from the calendar's one.

**Comment by sebbo2002** [comment]
I close this issue for now, please reopen if there are any questions left…

**Comment by bostondevin** [comment]
I vote for baking this in. Update the replicable structures and add them as maybe an includable js that just has it all in it. The community will enjoy - your the best so far on this.
