### ISSUE TITLE
Generated ICS is off by one hour in outlook.

### ISSUE THREAD

**Issue by lourencelinao** [sebbo2002/ical-generator#365]
I have different users from different timezones and I've noticed that for some timezones, the generated ical calendar is off by one hour in outlook. Please help.

**Comment by sebbo2002** [comment]
If you want to generate an event that takes place in every time zone at the same time, you can use [`floating(true)`](https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#floating).

**Comment by Dementor430** [comment]
Sorry to reopen this but Outlook now complains about floating mode only being supported by All Day Events. Is there any way to fix this?
