### ISSUE TITLE
Escaping double-quote characters

### ISSUE THREAD

**Issue by julianh2o** [sebbo2002/ical-generator#377]
Hey Sebbo,

Thanks for a wonderful package, this has been great for my project in working with external calendar apps.

One question, why are double quote characters being escaped (it seems like this is being done to various fields, but notably summary).

To reproduce:
```
calendar.createEvent({summary:'My "quoted" string'});
console.log(calendar.toString());
```

Is the double quote an illegal character in an ICS field? Most of the applications that I'm sending this ICS to are rendering the escape character. Eg.. `My \"quoted\" string`

Cheers,
Julian

**Comment by sebbo2002** [comment]
The `escape()` method currently seems to escape all strings as if they were enclosed in quotes. Which of course is not the case for fields like `summary` or `description`. I'll have a look at it during the week, but I might not get around to it until the weekend. Unfortunately I can't estimate that yet.

**Comment by julianh2o** [comment]
@sebbo2002 , thanks so much! Much appreciated :D
