### ISSUE TITLE
Incorrect typing for `event.start` in v3.5.0

### ISSUE THREAD

**Issue by dargmuesli** [sebbo2002/ical-generator#411]
[Upgrading to v3.5.0](https://github.com/maevsi/maevsi/pull/722) I face the linter error [`Type 'Moment' is missing the following properties from type 'ICalMomentTimezoneStub': tz, _isAMomentObject`](https://github.com/maevsi/maevsi/runs/7548582061?check_suite_focus=true#step:5:1618) on [`event.start`](https://github.com/maevsi/maevsi/blob/master/nuxt/server/api/ical.ts#L61).
I'm using ["moment": "2.29.4"](https://github.com/maevsi/maevsi/blob/db622c94d588cb4d8f0227e25d40d73904f106c6/nuxt/package.json#L74).

... what to do about it? Is [the new stub typing](https://github.com/sebbo2002/ical-generator/commit/56cffc7a4e9f741e779d445bfaf749b6885a4504) incorrect or am I doing something wrong?

**Comment by sebbo2002** [comment]
Oh yeah, that's definitely an error from the stub typings. I'll take a look...
