### ISSUE TITLE
Feature Request: Implement parsing (from ical string)

### ISSUE THREAD

**Issue by J-Zet** [sebbo2002/ical-generator#425]
Hi there,

first of all: great project, I really appreciate your work on it and it is of great use for me.

However so far I need an additional dependency just for parsing and then manually need to transform from the result object to an equivalent object of your project.

Is there any chance you implement parsing into this lib aswell?

Thanks & BR

**Comment by sebbo2002** [comment]
Honestly, I think parsing ical files is a completely different use case in most cases. I think that the use case of editing a ical file from a foreign source is also comparatively small, so I can't imagine this feature at the moment.

If the use case allows it, I would always recommend to save the JSON representation next to the ical file. This JSON can later be passed back into ical-generator and updated.

**Comment by dsl101** [comment]
I was going to ask about this too. The use case is handling the RSVP loop—ical generated and sent to people using this library then needs to read in their response. It would be great not to have 2 separate ical handling libraries, but if it's unlikely to be added, I guess that's the only way.

**Comment by tomaslundborg** [comment]
I am saving users events to a ics file, on S3. When there is a new event, I want to pull it from S3, add new event, then write it to S3 again, so users can stay subscribed to it. I assumed you could parse existing ical file. Maybe I am thinking about this in the wrong way... Is there a way to do what I need?

**Comment by sebbo2002** [comment]
@tomaslundborg `ical-generator` cannot parse ical files, it can only generate them. Hence the name. You can either also save a JSON representation (see [`ical.toJSON()`](https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalCalendar.html#toJSON)) and work with that to generate the new ical file, or use some other library to parse the ical file.
