### ISSUE TITLE
Support for Dates with no Time specified

### ISSUE THREAD

**Issue by grrbm** [sebbo2002/ical-generator#435]
Do you plan to support creating events with the dates only, like this:

DTSTART;VALUE=DATE:20221027
DTEND;VALUE=DATE:20221030

instead of:

DTSTART:20221027T000000Z
DTEND:20221030T000000Z

This seems to be the format used by airbnb iCal file nowadays

**Comment by sebbo2002** [comment]
If you want to create an all-day event, please use the [`allDay` parameter](https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#allDay):

```ts
'use strict';

import ical from 'ical-generator';

const cal = ical();

cal.createEvent({
    start: new Date(),
    end: new Date(),
    allDay: true, // ← that makes the difference
    summary: 'Example Event'
});

cal.toString();
```

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
BEGIN:VEVENT
UID:1f6267a9-eaa5-419f-89bc-d2f3680dfe5c
SEQUENCE:0
DTSTAMP:20221027T054025Z
DTSTART;VALUE=DATE:20221027
DTEND;VALUE=DATE:20221027
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-MICROSOFT-MSNCALENDAR-ALLDAYEVENT:TRUE
SUMMARY:Example Event
END:VEVENT
END:VCALENDAR
```

Feel free to reopen the ticket if you have further questions about this.
