### ISSUE TITLE
'Blob' refers to a value, but is being used as a type here

### ISSUE THREAD

**Issue by SMKH-PRO** [sebbo2002/ical-generator#446]
Hi! 👋 
Firstly, Thanks for your work on this project! 

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `ical-generator@3.6.0` for the project I'm working on.

Error:
'Blob' refers to a value, but is being used as a type here. Did you mean 'typeof Blob'?

<img width="1444" alt="Screenshot 2022-12-19 at 12 11 17 PM" src="https://user-images.githubusercontent.com/41765372/208368110-70537278-7e64-4217-b4d3-e79b3bca7ea1.png">

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/ical-generator/dist/calendar.d.ts b/node_modules/ical-generator/dist/calendar.d.ts
index c4f978f..783ff81 100644
--- a/node_modules/ical-generator/dist/calendar.d.ts
+++ b/node_modules/ical-generator/dist/calendar.d.ts
@@ -399,7 +399,7 @@ export default class ICalCalendar {
      *
      * @since 1.9.0
      */
-    toBlob(): Blob;
+    toBlob(): typeof Blob;
     /**
      * Returns a URL to download the ical file. Uses the Blob object internally,
      * so it's only supported in browsers supporting the Blob API.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sebbo2002** [comment]
Are you using a Blob polyfill? `typeof Blob` makes no sense for me, because `URL.createObjectURL` expects a `Blob` as parameter and not a `typeof Blob`. Can you provide a minimal example so that I can understand the error in isolation?
