### ISSUE TITLE
typescript compiler error TS1131: property or signature expected

### ISSUE THREAD

**Issue by senaki** [sebbo2002/ical-generator#449]
Typerscript version: 4.2.4
ical-generator version: 3.6.0

Description:

Typescript compiler fails with error code TS1131 at line 65 on `get isValid(): boolean` porperty in interface ICalLuxonDateTimeStub.

**Comment by sebbo2002** [comment]
Have you tried a recent Typescript version (4.9.x)? And if so, can you provide a minimal example that I can use to reproduce the error?

**Comment by senaki** [comment]
> Have you tried a recent Typescript version (4.9.x)? And if so, can you provide a minimal example that I can use to reproduce the error?

I'll try and say back.
