### ISSUE TITLE
Missing "RRULE:" prefix when adding repeating as string to event

### ISSUE THREAD

**Issue by davidruisinger** [sebbo2002/ical-generator#459]
Not sure if this is actually intended but we store rrules in our DB without `RRULE:` prefix. So e.g. `FREQ=WEEKLY;INTERVAL=4;WKST=MO`

If I now add this string to `event.repeating`, it is added 1to1 to the result (see [here](https://github.com/sebbo2002/ical-generator/blob/develop/src/event.ts#L1475))

Instead I would expect the generated ics string to add `RRULE:` as a prefix before the repeating string.

**Comment by sebbo2002** [comment]
Hey, thanks for your bug report. The feature was mainly intended to use external RRule generators. The generators I'm aware of automatically insert the `RRULE:` prefix. That's why I didn't come up with the idea at all. Thanks a lot.
