### ISSUE TITLE
`Email` field is required but marked as nullable in `ICalAttendeeData` type

### ISSUE THREAD

**Issue by koenigstag** [sebbo2002/ical-generator#467]
`ical-generator version: 3.6.1`

Recently tested simple email with attendees and discovered that none of falsy values are valid for email field in attendees array.
```typescript
interface ICalAttendeeData {
  ...
  email?: string | null;
  ...
}
```

Tested values are: undefined, null, "" (empty string).
Example code
``` typescript
attendees: [
  {
    name: "Test User",
    email: null
  }
]
```

This example gives an error:
```"No value for `email` in ICalAttendee given!"```

CodeSandbox:
https://codesandbox.io/s/express-typescript-example-forked-94ujl7?file=/src/routes.ts

**Comment by sebbo2002** [comment]
This is sadly true for all mandatory fields in ical-generator. The reason for this is that ical-generator has always allowed you to use the setters, in this case email() for example, and you are not required to include all the data with the constructor. This is currently absolutely valid code, for example:

```js
const attendee = event.createAttendee();
attendee.email('foo@bar.com');
```

I understand that this is a bit weird, but I hope that the exceptions is meaningful enough. For the next breaking version it is already planned that at least the mandatory fields have to be passed to achieve some security here.

**Comment by sebbo2002** [comment]
I just pushed a preview of `ical-generator` v6 to develop, which should fix this issue. I would be happy if you could test the new version and give me some feedback. You can install the version with `npm i ical-generator@next`. All changes in this release can be found [here](https://github.com/sebbo2002/ical-generator/wiki/Migration-Guide:-v5-%E2%86%92-v6).
