### ISSUE TITLE
remove dependency on fs, http

### ISSUE THREAD

**Issue by sousarka** [sebbo2002/ical-generator#478]
Hello,

First of all, thank you for the excellent library. Really appreciate this.

Is there any plan to decouple this from ```fs, http``` (node js specific libraries)? Since there are already helper methods like ```toString()/toBlob()/toJson()```, wanted to understand the reason behind the dependency to nodejs specific modules in this.

The specific save/serve methods can be in the readme if needed. 

Let me know your thoughts.

**Comment by sebbo2002** [comment]
Hello, `fs` has not been removed yet to preserve backward compatibility. In browser environments `fs` can be set to `null` by your bundler. Does this already solve your problem? `http` is only used for typing except in the unit tests, here the code could be adapted accordingly with `import type`.

**Comment by sousarka** [comment]
Hello, 
The only issue with setting `fs` to `null` in browser environment is the tools that most people work with in order to developer react/angular apps like `create-react-app` or `ng`, where developers can get all the simplified solutions without thinking of the bundler etc. In most cases, just to use this one library, they'll either have to eject the bundler out or try some other overrides (e.g. ```craco``` for react projects). This option may not be preferable for most developers since they'll not be able to use these packaged helpers (cra or ng) to upgrade/add-feature etc from that point onwards.

Let me know what you think.

**Comment by sebbo2002** [comment]
For the next minor release it is already planned to reduce dependencies. Removing `fs` is definitely one of them. But since there are also some other planned changes for this next major release (e.g. #344) and I have other projects with higher priority at the moment, it didn't happen yet.

**Comment by qertis** [comment]
> For the next minor release it is already planned to reduce dependencies. Removing `fs` is definitely one of them. But since there are also some other planned changes for this next major release (e.g. #344) and I have other projects with higher priority at the moment, it didn't happen yet.

I also want to note that the proposed option with Webpack configuration does not work with Vite. Because of what, it is not possible to work in this collector. Instead, errors are thrown:
```
[vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/ical-generator/dist/index.js:59:13: ERROR: No matching export in "browser-external:fs" for import "writeFile"
node_modules/ical-generator/dist/index.js:59:28: ERROR: No matching export in "browser-external:fs" for import "writeFileSync"
node_modules/ical-generator/dist/index.js:59:47: ERROR: No matching export in "browser-external:fs" for import "promises"
```

**Comment by sebbo2002** [comment]
In such a case I recommend to create a fork of this library (without `fs`), to use another library, or to do the creation of the calendar file server-side. I don't have the resources to work on the minor release at the moment.

**Comment by qertis** [comment]
> In such a case I recommend to create a fork of this library (without `fs`), to use another library, or to do the creation of the calendar file server-side. I don't have the resources to work on the minor release at the moment.

I have already created a library with such functionality, and it does not require any dependencies. You can use this library instead, as it avoids the need for fs altogether. 
https://www.npmjs.com/package/ical-browser

**Comment by 12joan** [comment]
> I also want to note that the proposed option with Webpack configuration does not work with Vite. Because of what, it is not possible to work in this collector. Instead, errors are thrown:

I'm using this patch (applied using patch-package) to make my app build correctly with Vite. Hope it helps! :heart:

[patches/ical-generator+5.0.1.patch](https://github.com/12joan/ical.rip/blob/81782500ae3dd9fff38d82fd6398fe4a99046824/patches/ical-generator%2B5.0.1.patch)

**Comment by sebbo2002** [comment]
I just pushed a preview of `ical-generator` v6 to develop, which should fix this issue. I would be happy if you could test the new version and give me some feedback. You can install the version with `npm i ical-generator@next`. All changes in this release can be found [here](https://github.com/sebbo2002/ical-generator/wiki/Migration-Guide:-v5-%E2%86%92-v6).

**Comment by 12joan** [comment]
[Upgrading to `v6.0.0-develop.1`](https://github.com/12joan/ical.rip/commit/fd0ed458cf35763565e459095b799c21f41f9c99) fixed the issue for me. Thanks! :heart:
