### ISSUE TITLE
Does not add organizer 'mailto' field if 'email' is not provided

### ISSUE THREAD

**Issue by gurupras** [sebbo2002/ical-generator#481]
Providing just `name` and `mailto` does not seem to generate the `mailto` value in the string content.

For example, if I were to call:
```js
cal.createEvent({
  ...
  organizer: {
    name: 'Turtle',
    mailto: 'no-reply@example.com'
  }
})
```
This ends up generating: `ORGANIZER;CN="Turtle"`

However, if I also throw in an email field:
```js
cal.createEvent({
  ...
  organizer: {
    name: 'Turtle',
    email: 'no-reply@example.com',
    mailto: 'no-reply@example.com'
  }
})
```
Then, I end up with: `ORGANIZER;CN="Turtle";EMAIL=no-reply@example.com:mailto:no-reply@example.com`

**Comment by sebbo2002** [comment]
It is sufficient to use only `email`. `mailto` exists only to overwrite the email again and is not needed in most cases.

```
cal.createEvent({
  ...
  organizer: {
    name: 'Turtle',
    email: 'no-reply@example.com'
  }
})
```

```
ORGANIZER;CN="Turtle":mailto:no-reply@example.com
```
