### ISSUE TITLE
Remix 1.16 can't build because of Ical polyfill

### ISSUE THREAD

**Issue by raskyer** [sebbo2002/ical-generator#488]
Hello,

First, thanks for your work on this great library. Really usefull!

We are (my company and me) on node 18.11 and was using Remix 1.15 to run our server with ical under the hood to create ics.
(Remix is a server side renderer of React).

We have update Remix to the latest version : 1.16 and now during the build we have: 
```
✘ [ERROR] No matching export in "node_modules/esbuild-plugin-polyfill-node/polyfills/empty.js" for import "writeFile"

    node_modules/ical-generator/dist/index.js:60:13:
      60 │ `,t}};import{writeFile as H,writeFileSync as W,promises as q}from"...
         ╵              ~~~~~~~~~


✘ [ERROR] No matching export in "node_modules/esbuild-plugin-polyfill-node/polyfills/empty.js" for import "writeFileSync"

    node_modules/ical-generator/dist/index.js:60:28:
      60 │ `,t}};import{writeFile as H,writeFileSync as W,promises as q}from"...
         ╵                             ~~~~~~~~~~~~~


✘ [ERROR] No matching export in "node_modules/esbuild-plugin-polyfill-node/polyfills/empty.js" for import "promises"

    node_modules/ical-generator/dist/index.js:60:47:
      60 │ ...ile as H,writeFileSync as W,promises as q}from"fs";var F=(g=>(g...
```

Remix has probably updated some configs on their hand or tweak some library for their build ? But maybe you know something about this. Currently, we can't use your library anymore. The build of remix is completly broken with it. And when removing your library the build works without issue.

There's not a lot of option for building ical in npm land. You are the only viable solution for production and I guess that's a lot of work for not much consideration (Joy of open source).
I would be glad to help if that's necessary, but I'd rather be honest, I'm not an expert of build issues. I'm wondering if you have some clue about what's going on and maybe potential fix ?

Thanks

**Comment by raskyer** [comment]
Nevermind, it seems to be purely related to Remix.

**Comment by sebbo2002** [comment]
Hi @raskyer, unfortunately I can't provide support for individual libraries that I never used, but if you find a bug or similar that causes this behavior, feel free to ping me. And thank you for your kind words 🥰
