### ISSUE TITLE
Question: Updating an existing ics file 

### ISSUE THREAD

**Issue by chaitanyaprem** [sebbo2002/ical-generator#50]
I would like to know if if the .ics file saved to the disk can be updated using this package. This way we can update the events in case of rescheduling or adding more attendees at later point in time. I couldn't find an API that would read from the ics file to create a ical object so that update for same event can be done.

**Comment by takkaria** [comment]
You might want to use the [ical](https://www.npmjs.com/package/ical) package for that.

**Comment by sebbo2002** [comment]
You can use `toJSON()` to save your calendar's state and update it, but it's not not implemented nor planned to parse ical files. As @takkaria mentioned, you can use other packages to solve this problem…

**Comment by KrisLau** [comment]
@chaitanyaprem What did you end up doing? I'm trying to create an ical link where the user can sync their personal calendar (Google, Apple, Outlook, etc) with the ical as events are added
