### ISSUE TITLE
Can't use Excluded Dates with RRule strings

### ISSUE THREAD

**Issue by royalty37** [sebbo2002/ical-generator#508]
Is there a reason why Excluded Dates (exclude) is a key on ICalRepeating options instead of ICalEventData? 

I want to be able to pass an RRule string and array of dates as exclusions (or even a comma seperated list) to the event.

I am however forced to parse the RRule string and build up this set of options instead which is more error prone.

This also leads to an additional issue. ByDay only allows for an ICalWeekday (or array) which only allows for 'MO', 'TU' and so on however an RRule string allows for ByDay entries such as '+3MO' which means I must also parse this and set both byDay and bySetPos which I am yet to determine whether or not it may cause any issues with more complex RRules.

Thanks in advance.

**Comment by sebbo2002** [comment]
I deliberately decided against this to keep the scope of the implementation small. Therefore, I deliberately implemented only a very small subset of functionality that covers ~80% of the use cases. For more complex tasks like yours, external rrule libraries like [rrule](https://www.npmjs.com/package/rrule) can always be used.

**Comment by sebbo2002** [comment]
I would close the ticket, if you have any objections or anything else you want to get off your chest, feel free to reopen it. Thank you very much.
