### ISSUE TITLE
Export a `browser` version

### ISSUE THREAD

**Issue by benmccann** [sebbo2002/ical-generator#511]
We had a user who wanted to use this package on Cloudflare Workers. The Node APIs are not available there so you can't import `node:fs`. It'd be nice if the other APIs could be made available without that functionality and import

You could make it available in the browser by exporting a smaller subset of APIs that has most of the functionality except for writing to files:
```
"exports": {
  "browser": "./my-browser-version.js",
  "require": "./my-cjs-version.cjs",
  "default": "./my-esm-version.js",
}
```

**Comment by lschloetterer** [comment]
Just FYI, I got it running in Cloudflare Workers by adding this in the package.json

```json
"browser": {
    "fs": false
}
```

**Comment by benmccann** [comment]
@cimnine does this work for you?

**Comment by cimnine** [comment]
Indeed 👍

**Comment by sebbo2002** [comment]
Since v6 has been released for a few days now, I'm closing this ticket. If there are still problems in the browser, feel free to open a ticket again.
