### ISSUE TITLE
Add DURATION property within the iCalEvent

### ISSUE THREAD

**Issue by eduardolandaiqmetrix** [sebbo2002/ical-generator#567]
If this is the wrong place to ask, please correct me. 

I'm trying to set a property called DURATION which I thought it was accepted as the unit tests include some values related to DURATION, but I was not able to find within the documentation an example on how to add DURATION for an event.  How could I add it?

Example: 

BEGIN:VEVENT
SUMMARY:Meeting with John
DTSTART:20240206T090000
**DURATION**:PT1H30M
END:VEVENT

Thank you,

**Comment by eduardolandaiqmetrix** [comment]
I found the sample and replicated it. Still it would be nice to have a solid sample.

**Comment by sebbo2002** [comment]
If someone should find this ticket by searching: Duration on events is currently not supported, please use `start` and `end` explicitly.

The situation is different for an alarm, where `DURATION` is supported and [can be set with `IcalAlarm.repeat()`](https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalAlarm.html#repeat).

Sorry for the confusion about the names of the methods. With this library, I am trying to avoid the need for prior knowledge of the ical standard, as I often find the names here not self-explanatory.
