### ISSUE TITLE
Edge case where GEO is defined but not added due to LOCATION title not present

### ISSUE THREAD

**Issue by titanism** [sebbo2002/ical-generator#569]
There is currently a bug here <https://github.com/sebbo2002/ical-generator/blob/9190c842f4e9aa9ac8fd598983303cb95e3cf76b/src/event.ts#L1753-L1774>.

As you can see, even if you provide a geo, because the title is not present, it won't get added to the output, and thus `GEO` won't be present due to missing LOCATION.

**Comment by sebbo2002** [comment]
I don't think I quite understand what you mean. Can you please post a concrete code example that does not work as desired?

**Comment by sebbo2002** [comment]
Can you please go into more detail about how you set a location without a title? This should not actually be possible. As you can see [here](https://github.com/sebbo2002/ical-generator/blob/9190c842f4e9aa9ac8fd598983303cb95e3cf76b/src/types.ts#L22), the title is a mandatory attribute and not optional. In my experiment, a correct error message is also displayed when I try something else:

**Example Code:**
```typescript
import ical from 'ical-generator';

const cal = ical();
const event = cal.createEvent({
  start: new Date()
});

event.location({
  geo: {
    lat: 52.51147570081018,
    lon: 13.342200696373846
  }
});

cal.toString();
```

**Output:**
```
Error: `location` isn't formatted correctly. See https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#location
```

**Comment by sebbo2002** [comment]
> This is strictly for the example of generating a ICS file from an object (e.g. one stored in a database).

Yes, but even then: For this library the `title` is a mandatory field and no output will be generated:

**Example Code:**

```javascript
import ical from 'ical-generator';

const someDatabaseObject = {
  events: [
    {
      start: new Date(),
      location: {
        geo: {
          lat: 52.51147570081018,
          lon: 13.342200696373846
        }
      }
    }
  ]
};

const cal = ical(someDatabaseObject);
cal.toString();
```

**Output:**
```
Error: `location` isn't formatted correctly. See https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#location
```

Please run your example to confirm.

> As far as I know, the RFC spec doesn't have the GEO being dependent upon a LOCATION.

This library produces RFC-compliant output, but as a developer I have a certain amount of leeway and don't have to allow every possibility in this API. On the contrary, I think a clear API helps many people to use this library more easily.

> e.g. using a library such as `node-ical`

The object format that may be passed to generate a calendar is precisely documented and differs from the JSON that `node-ical` generates when parsing. Therefore, the output of node-ical cannot be transferred directly to ical-generator. I recommend not to store the ical in the database, but the corresponding JSON representation, which can be generated with `toJSON()`:

**Example Code:**
```javascript
import ical from 'ical-generator';

const calA = ical({
  events: [
    {
      start: new Date()
    }
  ]
});

const savedInDb = calA.toJSON();

const calB = ical(savedInDb);
calB.toString();
```

**Output:**
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
BEGIN:VEVENT
UID:e6392bc0-45a6-4d5f-96b1-cb70044faeef
SEQUENCE:0
DTSTAMP:20240214T213111Z
DTSTART:20240214T213111Z
SUMMARY:
END:VEVENT
END:VCALENDAR
```

**Comment by sebbo2002** [comment]
> For the purposes of generating an ICS file, which this library implies it offers, it shouldn't arbitrarily deviate from the specification and require that in order to have GEO in your output, you must supply a LOCATION.

Please don't get me wrong, I think it's a good idea if we make the `title` optional in ical-generator. For me it was just important to understand if `ical-generator` currently pretends to support this somehow and only the generation of the ics is a problem - as it is implied in the PR description - or if it is currently not possible to specify a location without a `title` and therefore it is a technically new feature. The latter seems to be the case, that was my point. I apologize if there was any confusion.

If there are no objections, I would close this ticket now and clarify everything else in #570 so that there are no duplicate discussions on the same topic. Please let me know if there is still something open that is not part of #570.
