### ISSUE TITLE
ORGANIZER output in `toString()` could be improved

### ISSUE THREAD

**Issue by titanism** [sebbo2002/ical-generator#571]
Right now the conditionals don't make much sense at <https://github.com/sebbo2002/ical-generator/blob/9190c842f4e9aa9ac8fd598983303cb95e3cf76b/src/event.ts#L1793-L1798>.

Sometimes you have a `ORGANIZER` property line without a `EMAIL=` value, but it might have `CN` and a `mailto`.

This conditional only will output if you have `email`, and the `mailto` seems like it'll be off as well.

**Comment by sebbo2002** [comment]
Hi @titanism, thank you for you your issue and pull request. This library is aimed at developers who do not know much about the iCal format and therefore the attributes and field names within this library are not necessarily identical to the names in the iCal format. This has the advantage that the entry hurdle for beginners is low, but also the disadvantage that more experienced developers may not be able to cope with this library as well.

In this specific case, it is sufficient to simply use `email`. `ical-generator` then creates a corresponding `mailto` field. This is also specified [in the documentation](https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#organizer.organizer-2).

**Example:**

```typescript
import ical from 'ical-generator';

const cal = ical({});
cal.createEvent({
  start: new Date(),
  summary: 'John\'s Awesome Party',
  organizer: {
    name: 'John Doe',
    email: 'john@example.com'
  }
});

cal.toString();
```

**Output:**
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
BEGIN:VEVENT
UID:30d3d25e-c7c1-4bb3-bc1f-b96c1bc938c7
SEQUENCE:0
DTSTAMP:20240215T082610Z
DTSTART:20240215T082610Z
SUMMARY:John's Awesome Party
ORGANIZER;CN="John Doe":mailto:john@example.com
END:VEVENT
END:VCALENDAR
```

I understand that this is difficult for developers who want to work close to the ics standard, but the target group chosen here is simply a different one and you will never be able to please both target groups 100%. However, I would recommend developers who want to work close to the standard to use an appropriate library (e.g. `ics`).

I hope I was able to clarify your request and would therefore close the ticket and your pull request. Please let me know here if I have overlooked anything. Thank you very much.
