### ISSUE TITLE
Attendee missing from ICalAlarmData

### ISSUE THREAD

**Issue by titanism** [sebbo2002/ical-generator#573]
https://github.com/sebbo2002/ical-generator/blob/c6d2f1f9909930743acb54003e124faea4f58cec/src/alarm.ts#L115

The prop `attendee` is missing, and it would be a value such as `mailto:foo@gmail.com`

**Comment by sebbo2002** [comment]
I like your suggestion and have summarized it under #{number}, as your three tickets together are actually one coherent feature. I hope that's okay with you.

**Comment by sebbo2002** [comment]
> @sebbo2002 there's no mention of `attendee` in #576 yet (?)

It's not mentioned because you can't use `EMAIL` without attendee. Same for summary, which is also a required field for email alarms.
