### ISSUE TITLE
ICalAlarmType missing `email` type

### ISSUE THREAD

**Issue by titanism** [sebbo2002/ical-generator#574]
`email` is missing from `type` enumerable list of Strings

<https://github.com/sebbo2002/ical-generator/blob/c6d2f1f9909930743acb54003e124faea4f58cec/src/alarm.ts#L16-L19>

**Comment by sebbo2002** [comment]
I like your suggestion and have summarized it under #{number}, as your three tickets together are actually one coherent feature. I hope that's okay with you.
