### ISSUE TITLE
Allday timezone issue

### ISSUE THREAD

**Issue by pezza3434** [sebbo2002/ical-generator#580]
Hi everyone,

First of all, great work on this package. Been using this on production for a number of years with few issues.

I've come across a dreaded timezone issue with 'allday' events.

In the tests we have this code:

```      
describe('Issue #38', function () {
    it('should work with Europe/Berlin', function () {
        const calendar = ical({
            prodId: '//superman-industries.com//ical-generator//EN',
            timezone: 'Europe/Berlin',
            events: [{
                start: moment('2016-04-30T22:00:00.000Z'),
                summary: 'Example Event',
                allDay: true
            }]
        });

        const str = calendar.toString();
        assert.ok(str.indexOf('DTSTART;VALUE=DATE:20160501') > -1);
    });
```

What I've noticed is this doesn't work if the timezone is defined on the event rather then the 'higher/global' level i.e:

```      
 it('should work with Europe/Berlin', function () {
      const calendar = ical({
          prodId: '//superman-industries.com//ical-generator//EN',
          events: [{
              start: moment('2016-04-30T22:00:00.000Z'),
              summary: 'Example Event',
              timezone: 'Europe/Berlin',
              allDay: true
          }]
      });
```

The other thing that's strange is it only works if you pass in a moment object (like the test). If you pass in a native date object like this:

```
const start = new Date(0);
const end = new Date(0);
start.setUTCSeconds(startUtc);
end.setUTCSeconds(endUtc);

cal.createEvent({
    start,
    end,
    summary: event.summary,
    description: icsDescription,
    allDay: event.isAllDayEvent,
    location: event.location && event.location.description
});
```

It also does not work.

Hmm....

**Comment by sebbo2002** [comment]
> First of all, great work on this package. Been using this on production for a number of years with few issues.

Thank you.

> What I've noticed is this doesn't work if the timezone is defined on the event rather then the 'higher/global' level i.e:

Ouch. You are absolutely right, sorry for that. I'll take care of it by the weekend at the latest.

> The other thing that's strange is it only works if you pass in a moment object (like the test)

Can you provide a full example for this with the expected output? I tested this code and I get an allday response:

```typescript
import ical from 'ical-generator';
import assert from 'node:assert';

const calendar = ical({
    prodId: '//superman-industries.com//ical-generator//EN',
    events: [{
        start: new Date('2016-05-01T03:00:00.000Z'),
        timezone: 'Europe/Berlin',
        summary: 'Example Event',
        allDay: true
    }]
});

calendar.toString();
```

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//superman-industries.com//ical-generator//EN
BEGIN:VEVENT
UID:ef30114d-0af6-4773-a520-a6ad8309642a
SEQUENCE:0
DTSTAMP:20240228T183800Z
DTSTART;VALUE=DATE:20160501
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-MICROSOFT-MSNCALENDAR-ALLDAYEVENT:TRUE
SUMMARY:Example Event
END:VEVENT
END:VCALENDAR
```

**Comment by sebbo2002** [comment]
Okay, sorry for the confusion. I assumed yesterday that `TZID` was missing. But I [checked the spec again](https://icalendar.org/iCalendar-RFC-5545/3-2-19-time-zone-identifier.html), and I think `TZID` usage is not defined for all day events (value type `DATE`):

> This parameter MUST be specified on the "DTSTART", "DTEND", "DUE", "EXDATE", and "RDATE" properties when either a DATE-TIME or TIME value type is specified and when the value is neither a UTC or a "floating" time

So the output from ical-generator is correct as all day events can not have a time zone. Or have I misunderstood something?

**Comment by sebbo2002** [comment]
Hey, I'll close this issue for now, if I misunderstood something please let me know.
