### ISSUE TITLE
DTSTAMP should check the floating property

### ISSUE THREAD

**Issue by grundid** [sebbo2002/ical-generator#587]
Right now the DTSTAMP is always output as UTC time. However the spec says that it is a DATE-TIME value type. Therefore it should allow floating, TZ and UTC dates.
Could you please align DTSTAMP with the other DATE-TIME properties?

**Comment by sebbo2002** [comment]
According to iCal Spec / RFC 5545, `DTSTAMP` **must** be specified in UTC:

> [3.8.7.2](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.7.2).  Date-Time Stamp
> 
> Property Name:  DTSTAMP
>
> Value Type:  DATE-TIME
> Description:  The value MUST be specified in the UTC time format.

Therefore ical-generator is compliant at this point. If you see it differently and can find evidence of this in the spec, please let me know.

**Comment by grundid** [comment]
Thank you for pointing this out. The Value Type is somehow misleading here. And thanks for the great library.
