### ISSUE TITLE
Incorrect Formatting Show on Firefox & Tor (Fine with Chrome & IE)

### ISSUE THREAD

**Issue by Buckaroo9** [sebbo2002/ical-generator#59]
Had some strange formatting with the input bars on Firefox and Tor, can anyone repeat?
Running Firefox 52.0 on a 1920x1080 screen at 100% zoom.
![ical view](https://cloud.githubusercontent.com/assets/21959742/24068446/3ff0eeb4-0b65-11e7-8b34-c61b83865a45.PNG)

**Comment by ocelotsloth** [comment]
You should report this issue over at https://git.gmu.edu/srct/gmucal-legacy/ ....this project is entirely unrelated to that site.
