### ISSUE TITLE
Respect timezone of Luxon DateTime instance when rendering an allday event

### ISSUE THREAD

**Issue by cimnine** [sebbo2002/ical-generator#592]
I store dates as ISO timestamps, like `2024-03-17T00:00:00.000+01:00`. When I add an all day _event_ to a _calendar_ like in the following example, it is rendered as `20240316` in the _ical_ format, but `20240317` would be my expectation.

```js
const cal = new ICalCalendar();
const luxonStartDate = DateTime.fromISO('2024-03-17T00:00:00.000+01:00', { setZone: true });
const luxonEndDate = DateTime.fromISO('2024-03-18T00:00:00.000+01:00', { setZone: true });
const event = new ICalEvent({
  allDay: true,
  start: luxonStartDate,
  end: luxonEndDate,
}, cal);

const actual = event.toString();
// actual:
// DTSTART;VALUE=DATE:20240316
// DTEND;VALUE=DATE:20240317

// expected:
// DTSTART;VALUE=DATE:20240317
// DTEND;VALUE=DATE:20240318
```

This does not happen, when the `cal` object is given a fixed timezone, like `cal.timezone('Europe/Zurich')`. But that only works if all `DateTime` instances are in that same timezone – which they might not be in my case. Therefore, my instances of `ICalCalendar` don't have a timezone set, yet still I expect that the timezone which is embedded in the `DateTime` instance is respected.

I've created a PR with just some test (for now) to further explain my situation as unit tests: https://github.com/sebbo2002/ical-generator/pull/591
In order to fix it, I'm unsure whether it needs to be addressed in `event.ts#toString()` or in `tools.js#formatDate()`.

**Comment by sebbo2002** [comment]
Ah cool, I didn't know you could save the time zone in a `DateTime` object. I actually only work with UTC, maybe that's why. This is not supported yet, I always assumed that the objects were already adjusted to the local time when I get them in ical-generator. Thank you.
