### ISSUE TITLE
Ability to parse existing *.ics file into an ICalCalendar class

### ISSUE THREAD

**Issue by Timebutt** [sebbo2002/ical-generator#595]
Is there a way to parse an iCal file/string into an `ICalCalendar` class using `ical-generator`?

Context: in my current application, I'm supporting an endpoint that generates *.ics files. Some of my clients are calling the endpoint very frequently, which triggers the calculation of the entire calendar file even when there might have been no changes to events. You can imagine this is an ideal scenario to set up caching. At the end of the calculation I'm storing the *.ics file as a static asset in a bucket. Once a new request comes in, I want to fetch all updated events, grab the previously generated *.ics file and update those events. The issue I'm facing now however, is that I don't know how to do the inverse operation: how can I go from an *.ics file or a string to an `ICalCalendar` object, so that I can do the update?

Thinking more on this, I would also need a `deleteEvent()` method, or `updateEvent()` method for this to really work.
I'm wondering what your stance on this is, should `ical-generator` remain a one-way library (code -> iCal file) as it is right now, or are you  considering changes like these?

Kind regards,
Nils

**Comment by sebbo2002** [comment]
Thank you for your ticket. `ical-generator` is only intended as a simple generator of ics files. Parsing such files is not part of it and not planned in the medium term, as it would have very little in common with the current code base. Perhaps it could help you to export the calendar with `toJSON()` and then regenerate it. However, you would then have to manage the JSON yourself. Otherwise, there are already many other ics parsers that will hopefully be able to help you. Sorry, you were probably hoping for a different answer.

**Comment by Timebutt** [comment]
Thanks for your very quick reply @sebbo2002! The `toJSON()` approach sounds interesting, I'll take a look at how easily I could set something like that up. In case I get it done, would `createICalCalendarFromJSON()` function be be a utility you'd see as part of this repository?

**Comment by sebbo2002** [comment]
`toJSON()` result can be used for `ical()` or the `ICalCalendar` constructor, so re-importing is already supported:

```typescript
import ical from 'ical-generator';
const calendar = ical();

// do your magic

const json = calendar.toJSON();

// save or mutate json

const newCalendar = ical(json);
newCalendar.toString();
```

**Comment by Timebutt** [comment]
Ah but that's perfect! I can very easily store the calendar as `JSON` instead of an actual `*.ics` file, in fact it'll even be a smaller file to store I think. Perfect solution, you made my day ;)

I'll just strip out the events I want to regenerate in the `// do your magic part` and then just `createEvent()` to readd them, wonderful!
