### ISSUE TITLE
Classes appear on calendar after the last day of classes for semester?

### ISSUE THREAD

**Issue by Buckaroo9** [sebbo2002/ical-generator#60]
Could we have the software grab the correct last date of classes, or possibly have the user manually input the end date for the repetition?

**Comment by ocelotsloth** [comment]
@Buckaroo9 I'm confused as to what you're asking here...are you sure this is an issue with the NPM module?

**Comment by ocelotsloth** [comment]
Just as a shot in the dark....looking at how you have starred a couple of @srct 's projects, are you talking about schedules.gmu.edu? If so you should report this issue over at https://git.gmu.edu/srct/gmucal-legacy/
