### ISSUE TITLE
Support for repeating events byDay with "1WE" and similar

### ISSUE THREAD

**Issue by MTRNord** [sebbo2002/ical-generator#601]
https://icalendar.org/rrule-tool.html allows generating "1WE" and friends to indicate to repeat on the first Wednesday of the month. (`FREQ=MONTHLY;INTERVAL=1;BYDAY=1WE`). However, the lib seems to not allow any of the number prefixes. This is in my usecase quite limiting. Could this be added to the allowed values by any chance?

**Comment by MTRNord** [comment]
:facepalm: I just realised thats what `byMonthDay` is for. Oops

**Comment by MTRNord** [comment]
Actually I was trigger happy.

`byMonthDay: [1]` doesnt seem to do what `byDay: "1WE"` would be doing :thinking: At least if thunderbird is correctly parsing it.

**Comment by MTRNord** [comment]
byMonthDay seems to mean "every month on a Wednesday which falls on the 1." while 1WE means "every month of the first occurance of a Wednesday in that month"

**Comment by sebbo2002** [comment]
Your use case is currently not directly covered by `ical-generator`. The options here are very limited to the most obvious use cases. However, you can use the [`rrule`](https://github.com/jkbrzt/rrule) module if you want to cover more complex scenarios. They also have a [very great online demo](https://jkbrzt.github.io/rrule/). If I have understood you correctly, your rule would look like this in `ical-generator`:

```typescript
import ical from 'ical-generator';
import { RRule } from 'rrule';

ical({
  events: [{
    start: new Date(),
    summary: 'Test Event',
    repeating: new RRule({
      freq: RRule.MONTHLY,
      byweekday: [RRule.WE.nth(1)]
    })
  }]
}).toString();
```

```ical
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
BEGIN:VEVENT
UID:fae5557e-1602-4a13-9d66-e46decfd1616
SEQUENCE:0
DTSTAMP:20240705T115746Z
DTSTART:20240705T115746Z
RRULE:FREQ=MONTHLY;BYDAY=+1WE
SUMMARY:Test Event
END:VEVENT
END:VCALENDAR
``` 

Does that solve your problem?

**Comment by MTRNord** [comment]
Hi thanks this seems to indeed solve my issue :) Thanks a lot!
