### ISSUE TITLE
timezone confusion

### ISSUE THREAD

**Issue by tcurdt** [sebbo2002/ical-generator#604]
This gives me

```
          const start = luxon.DateTime.fromFormat(date, "dd.MM.yyyy")
            .set({ hour: 19, minute: 0, second: 0, millisecond: 0 })
            .setZone("Europe/Berlin");
          console.log(start);

          DateTime { ts: 2024-08-30T19:00:00.000+02:00, zone: Europe/Berlin, locale: en-US }
```

which looks fine. I add this as a start to an event in a calendar

```
    const cal = new ICalCalendar({
      name: "...",
      description: "...",
      url: "",
      method: ICalCalendarMethod.PUBLISH,
      timezone: "Europe/Berlin",
    });
```

and the relevant parts of the  ICS looks like this:

```
TIMEZONE-ID:Europe/Berlin
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VEVENT
...
DTSTAMP:20240816T132817
DTSTART:20240830T190000
DTEND:20240830T230000
```

but iCal shows this as 21:00 instead of 19:00. Is the TZID missing maybe?

What would be the correct way to fix this?

**Comment by aduros** [comment]
I also struggled with timezones, here's what seemed to work for me:

```
import { ICalCalendar } from 'ical-generator'
import { tzlib_get_ical_block } from 'timezones-ical-library'

const cal = new ICalCalendar({
  timezone: {
    name: 'America/New_York',
    generator: (tzName) => tzlib_get_ical_block(tzName)[0],
  },
})

cal.createEvent({
  start: new Date(),
  summary: 'Hello world',
  timezone: 'America/New_York',
})
```

**Comment by sebbo2002** [comment]
By default, all times are displayed in UTC. A note on this can be found [in the readme](https://github.com/sebbo2002/ical-generator#-date-time--timezones). This should not really be an issue at all. Does this cause problems for you in a client? Or why do you want to have local timestamps?

**Comment by tcurdt** [comment]
Using UTC for physical events does not work too well. In the end they are happening at local time.
But maybe it's simpler to create the date as local time, then convert it to UTC and then use that in the ical event.

Sounds like that could work around the problems.

I am still a bit stumped by the behaviour I documented in this issue though.
If times are expected in UTC wouldn't it make sense to convert to UTC by default?

**Comment by sebbo2002** [comment]
> Using UTC for physical events does not work too well. In the end they are happening at local time.

Every iCal client I know will display the date and time in the local time, even if defined in UTC internally.

> If times are expected in UTC wouldn't it make sense to convert to UTC by default?

They will. For Luxon objects ical-generator will execute `.setZone('utc')`. Only if `timezone` is specified, this timezone will be set instead. Reference: https://github.com/sebbo2002/ical-generator/blob/develop/src/tools.ts#L66

**Comment by tcurdt** [comment]
Digging deeper it seems it was the `timezone` setting on the calendar itself to caused the problems.

    const cal = new ICalCalendar({
      // timezone: "Europe/Berlin",
    });

Removing this seem to fix all this with the times in the ical file being UTC.

**Comment by tcurdt** [comment]
So it seems the _real_ problem was really the Luxor API. It creates the date in local time (which is UTC on my server) but `setZone` is overly smart and does an actual conversion unless you force it **not** to.

```
          const start = luxon.DateTime.fromFormat(date, "dd.MM.yyyy")
            .set({ hour: 19, minute: 0, second: 0, millisecond: 0 })
            // .setZone("Europe/Berlin")
            .setZone("Europe/Berlin", { keepLocalTime: true })
```

All in all a bit confusing. Hope this helps whoever finds the issue.
Thanks for the help. Closing!

**Comment by Ciupic24** [comment]
[]mony50000000 €
