### ISSUE TITLE
What client do you use for webcal/ical link ?

### ISSUE THREAD

**Issue by AntoineTurmel** [sebbo2002/ical-generator#61]
This is not really an issue for this project, more like a question, what client do you use to fetch your webcal/ical links ?
Thunderbird is fine since you can define the time to refresh the ical, but other apps like Google Calendar/Nextcloud/Owncloud tend to have a long cache time and are not showing updates/new events.

I use to restart my node.js script to update/add my events... maybe it's not the right thing to do, but Thunderbird is keeping up so it's working.

**Comment by sebbo2002** [comment]
I use the native Calendar on macOS mainly. Sorry for the delay…
