### ISSUE TITLE
GEO field can break Google Calendar import

### ISSUE THREAD

**Issue by Timebutt** [sebbo2002/ical-generator#618]
I got a report from some of my customers that my calendar integration wasn't working for some people when they subscribed to my iCal feed in Google Calendar. The iCal file I generate validated correctly on a few of the online tools out there, and there were no issues when subscribing in Apple Calendar or Outlook. I started investigating (which meant cavemanning, Google Calendar doesn't exactly throw a stacktrace when the import goes wrong), and found Google Calendar breaks on this line of the `*.ics` file `ical-generator` builds:

```
GEO:null;null
```

Below demo calendar file is what you can use to validate my statement. If you go to Google Calendar, go to Settings and then import this file, you'll be greeted with a dialog saying Google Calendar can't import the events from the file.

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Test//iCal Sync//EN
NAME:Test
X-WR-CALNAME:Test
REFRESH-INTERVAL;VALUE=DURATION:PT6H
X-PUBLISHED-TTL:PT6H
BEGIN:VEVENT
UID:2MIfT3GAVqBxqxKI7RUz
SEQUENCE:0
DTSTAMP:20241009T074546Z
DTSTART;VALUE=DATE:20250317
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-MICROSOFT-MSNCALENDAR-ALLDAYEVENT:TRUE
SUMMARY:Event Title
GEO:null;null
END:VEVENT
END:VCALENDAR
```

I haven't read `RFC2445` yet to verify if `GEO:null;null` is a valid field yet, but as the validators seem to accept it either they are too lax, or Google is too strict in their implementation. Be that as it may: in the real world this results in a broken `ics` file so I think we have to do something here.

Easiest fix would be to omit the field if it's clearly empty (you can verify this, removing the line and importing the file works fine in Google Calendar), but I'm sure as to what you think is the best way forward?

I will patch this on my end for now, as I have clients waiting for a fix, but I'm happy to help implement a solution to mitigate this!

Edit: I was able to fix this fairly easily on my end by checking if the values I pass into `location.geo` actually exist. You could argue it's the developer responsibility to not pass in non-existing values, then again the library should not be able to generate invalid `ics` files either.

**Comment by sebbo2002** [comment]
Hi, can you provide a minimalistic example that produces your `GEO:null;null` output? Otherwise, unfortunately, I can't really reproduce it.

### No location

``` typescript
import ical from 'ical-generator';

const cal = ical();

cal.createEvent({
  summary: 'Test 1',
  start: new Date(),
  location: null
});

cal.toString();
```

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
BEGIN:VEVENT
UID:0154906d-e7ff-4724-83b0-84815b0294ab
SEQUENCE:0
DTSTAMP:20241010T140503Z
DTSTART:20241010T140503Z
SUMMARY:Test 1
END:VEVENT
END:VCALENDAR
```


### With location.geo = null (invalid)

``` typescript
import ical from 'ical-generator';

const cal = ical();

cal.createEvent({
  summary: 'Test 1',
  start: new Date(),
  location: {
    geo: null
  }
});

cal.toString();
```

```
Error: `location` isn't formatted correctly. See https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#location
```


### With location.geo.lat|lng = null (invalid)

``` typescript
import ical from 'ical-generator';

const cal = ical();

cal.createEvent({
  summary: 'Test 1',
  start: new Date(),
  location: {
    geo: {
      lat: null,
      lng: null
    }
  }
});

cal.toString();
```

```
Error: `location` isn't formatted correctly. See https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#location
```

**Comment by Timebutt** [comment]
I currently don't have the code base on hand, but if I'm not mistaken this was what I was passing in:

```
{
   "location":{
      "geo":{
         "lat":"undefined",
         "lng":"undefined"
      }
   }
}
```

I can take a look tonight in the codebase if this doesn't turn out to reproduce the issue

**Comment by sebbo2002** [comment]
This also produces an error for me. So please have a look tonight or in the next few days. If it is a valid usage according to the API description, the output should of course also be valid and not `null;null`.

``` typescript
import ical from 'ical-generator';

const cal = ical();

cal.createEvent({
  summary: 'Test Event',
  start: new Date(),
  location: {
    geo: {
      lat: "undefined",
      lng: "undefined"
    }
  }
});

cal.toString();
```

```
Error: `location` isn't formatted correctly. See https://sebbo2002.github.io/ical-generator/develop/reference/classes/ICalEvent.html#location
```

**Comment by Timebutt** [comment]
Just took a quick look at my exact code, because indeed your example throws the same error when I run it.
The exact object I pass in for `location` was this:

```
"location":{
   "title":"Empty Venue",
   "address":null,
   "geo":{
      "lat":null,
      "lon":null
   }
}
```

The documentation seems to mention there are two types for `location`, one with and one without title. Extrapolating that makes me think there are two code paths, and the one with title is the one happily accepting the `null` for both `lat` and `lon`?

**Comment by sebbo2002** [comment]
Okay, let's go through that one by one:

- As you rightly say, you use the interface [ICalLocationWithTitle](https://sebbo2002.github.io/ical-generator/develop/reference/interfaces/ICalLocationWithTitle.html) for the title
- [`address`](https://sebbo2002.github.io/ical-generator/develop/reference/interfaces/ICalLocationWithTitle.html#address) is defined here as `string | undefined`. `null` is therefore not a valid value
- Same applies for `geo`. It can either be a [ICalGeo](https://sebbo2002.github.io/ical-generator/develop/reference/interfaces/ICalGeo.html) object (with `lat` and `lon` number values!) or undefined.  Filling the `ICalGeo` object with `null` values is not defined.
- Your problem occurs because the validation does not check for `null`, as this value is not allowed (`isFinite(null) === true`). From this point of view, it is not a bug. Of course, I would still adjust this in the medium term if it has already been noticed.
- I would recommend using more typesafe environments such as Typescript in the future to avoid such errors as far as possible.

**Comment by Timebutt** [comment]
Interesting! Don't worry, I only write code in TypeScript but unfortunately in this codebase I don't have `strict: true` which would have definitely caught this issue. That being said, lots of codebases out there are not running in strict mode, or are using plain JavaScript. I think the only question is: is `GEO:null;null` a valid value according to the official specification. If it isn't, I feel the library should never be able to generate this and should be more robust in terms of what people can pass into the `createEvent()` function.

Now to make my codebase strict ;)

**Comment by Timebutt** [comment]
Thanks for the fix! I'm hoping this prevents other people from debugging huge iCal files that don't work in Google Calendar ;)
