### ISSUE TITLE
Can't import URL to any calendar

### ISSUE THREAD

**Issue by kvdmolen** [sebbo2002/ical-generator#62]
Hi,

I've setup the first example. It works, I can download the event, but I can't feed the URL to my Google Calendar.

Is this a bug or a non-existing feature?

**Comment by AntoineTurmel** [comment]
Hmm have you tried listening to 0.0.0.0 instead of 127.0.0.1 ?

**Comment by kvdmolen** [comment]
I'm serving it in an online environment (to be able to load into Google Calendar). So I only have an API URL.

Code Snippet:

```js
app.get("/ical", function(req, res) {
    var cal = ical({...})
    cal.serve(res)
})

app.listen(3000)
```

Works for downloading the `ics` file but not for URL import in calendar..

**Comment by sebbo2002** [comment]
Can't reproduce, can you provide us a test URL?

**Comment by kvdmolen** [comment]
https://www.fundo.co/ical/14991 (this will download the `.ics` directly)

**Comment by AxelTheGerman** [comment]
The URL does no longer work, but just to double check. Did you set the correct headers on the response?

Example from a blog post using a different library
```
   let iCalString = iCal.toICSString();

    res.set('Content-Type', 'text/calendar;charset=utf-8');
    res.set('Content-Disposition', 'attachment; filename="worktile.pro.calendar.my.ics"');
    res.send(iCalString);
```

Also I think Google Calendar requires a `.ics` URL
