### ISSUE TITLE
Error in webpack

### ISSUE THREAD

**Issue by Regaddi** [sebbo2002/ical-generator#64]
Hi,

when trying to require ical-generator via `const ical = require('ical-generator');` webpack throws the following error:

```
ERROR in ./~/ical-generator/lib/calendar.js
Module not found: Error: Can't resolve 'fs' in '/my-project/node_modules/ical-generator/lib'
 @ ./~/ical-generator/lib/calendar.js 411:8-21 425:15-28
 @ ./~/ical-generator/lib/index.js
 ...
```

Can't get it up and running 😢

**Comment by Regaddi** [comment]
Nevermind. It was totally webpack related and had nothing to do with your package 😄

**Comment by rally25rs** [comment]
@Regaddi do you remember what you did to "fix" this? Did you just have webpack ignore the `fs` package?

**Comment by sebbo2002** [comment]
@rally25rs I'll add this to the docs later, thank you!

**Comment by CoffeyMachine** [comment]
This solution worked for me with Angular 8 (without Ivy)
https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d

**Comment by djplaner** [comment]
Seems recent updates to webpack break the previous solution.  The error I was seeing 

```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node has an unknown property 'fs'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
```

The solution that worked for me is [from StackOverflow](https://stackoverflow.com/questions/64361940/webpack-error-configuration-node-has-an-unknown-property-fs).  Add the following to webpack configuration

```
resolve: {
  fallback: {
    fs: false
  }
}
```

**Comment by sebbo2002** [comment]
@djplaner Thanks for your note, I updated the readme in https://github.com/sebbo2002/ical-generator/commit/ee2cb70b7dfd0085a24a8700213deb97c57fe400
