### ISSUE TITLE
"\r\n " is wrongly inserted in attendee email

### ISSUE THREAD

**Issue by ykorach** [sebbo2002/ical-generator#67]
Hey I create event with the following code:
```
createGmailCalenderEVent = (options) => {
        let cal = ical();
        let event = cal.createEvent({.....})
        event.createAttendee({email: options.email, name: options.name});
        console.log(cal.toString());
    }
```
this is will log :
```
BEGIN:VCALENDAR
VERSION:2.0
....
ATTENDEE;ROLE=REQ-PARTICIPANT;CN="John Doe":MAILTO:john@gmail.c
 om
END:VEVENT
END:VCALENDAR
```
("\r\n " is wrongly inserted between ".c" and "om" )
off course i logged the `options.email, name: options.name`  before and they looked fine, 
Am I missing anything?

**Comment by AndrewLane** [comment]
Are you sure it's not just working how the RFC-5545 spec says it should work as far as max lengths of lines?

https://tools.ietf.org/html/rfc5545#section-3.1

**Comment by ykorach** [comment]
OK , so this is what I was missing...
Thank's a lot @AndrewLane !

**Comment by AndrewLane** [comment]
@ykorach you can probably close this PR, right?
