### ISSUE TITLE
htmlDescription not outputting

### ISSUE THREAD

**Issue by MDrooker** [sebbo2002/ical-generator#73]
Seems like this line -
var attributes = ['id', 'uid', 'sequence', 'start', 'end', 'timezone', 'stamp', 'timestamp', 'allDay', 'floating', 'repeating', 'summary', 'location', 'description', 'organizer', 'attendees', 'alarms', 'method', 'status', 'url'],
  
is Missing the 'htmlDescription' attribute...so it wont output toString()

I added it-
var attributes = ['id', 'uid', 'sequence', 'start', 'end', 'timezone', 'stamp', 'timestamp', 'allDay', 'floating', 'repeating', 'summary', 'location', 'description', 'htmlDescription', 'organizer', 'attendees', 'alarms', 'method', 'status', 'url'],
  
Now it does.
Will do a PR.

**Comment by sebbo2002** [comment]
Thanks @opravil-jan for fixing this in #79. 👌🏼
