### ISSUE TITLE
Don't rely on non-standard RegExp.$1-$9

### ISSUE THREAD

**Issue by benglass** [sebbo2002/ical-generator#76]
Nice library, was going to use it but can't because we are using babel to transpile our code and the way this project uses RegExp.$1 seems to be incompatible with babel compilation. This is a non-standard feature and does not appear to be working in combination with babel compilation. 

From MDN

**"This feature is non-standard and is not on a standards track"**

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n

**Comment by AndrewLane** [comment]
@benglass  This seems like a pretty easy thing to fix.  Are you working on a PR to fix this?  If not, I can probably throw one in.

**Comment by benglass** [comment]
@AndrewLane Agreed, should be an easy fix. I'm not working on a PR as we ended up using a different ical package due to this issue but if this gets addressed here we might switch to use this one as we like that it only relies on moment whereas the other package relies on more deps.

**Comment by AndrewLane** [comment]
Hopefully https://github.com/sebbo2002/ical-generator/pull/77 is the fix you were looking for, @benglass

**Comment by benglass** [comment]
@AndrewLane just what I had in mind! Hope this lands in a release soon!

**Comment by sebbo2002** [comment]
Pull Request merged. Due to my bachelor thesis, I currently lack in releasing the version. See #72 for the current state for ical-generator 3.0.
