### ISSUE TITLE
why my RSVP button didnot show?

### ISSUE THREAD

**Issue by qxl1231** [sebbo2002/ical-generator#78]
![image](https://user-images.githubusercontent.com/8305742/35130416-b514be40-fcfb-11e7-8c5e-a01245b105e3.png)
![image](https://user-images.githubusercontent.com/8305742/35130417-b6c47050-fcfb-11e7-90b3-c643de2ad2de.png)
 
where is the problem? needs help, 3Q

**Comment by qxl1231** [comment]
pic 2 is the result i need, but my ical didnot show this 3 button

**Comment by sebbo2002** [comment]
Please provide a code example, otherwise it would be pure error guessing.

**Comment by sebbo2002** [comment]
Please reopen this issue in case you are still affected by this issue and you are able to provide some example code. Tank you.

**Comment by qxl1231** [comment]
yes,it not resolved. the code is 

`
var ical = require('ical-generator');

var calIns = ical({
  prodId: '//superman-industries.com//ical-generator//EN',
  method: 'request',
  CALSCALE: 'GREGORIAN',
  events: [
    {
      sequence: 2,
      start: new Date(),
      end: new Date(new Date().getTime() + 3600000),
      timestamp: new Date(),
      summary: 'My Event',
      location: '上海',
      status: 'TENTATIVE',
      // "X-MICROSOFT-CDO-IMPORTANCE":1,
      organizer: {name: 'CN=west', email: 'n@research.xbmail.com.cn'},
      attendees: [
        {
          name: '龙',
          ROLE: 'REQ-PARTICIPANT',
          RSVP: true,
          status: 'tentative',
          email: 'q@research.xbmail.com.cn'
        },
        {name: '杨', ROLE: 'REQ-PARTICIPANT', RSVP: true, status: 'tentative', email: 'xx@qq.com'}
      ],
    }
  ]
}).toString();

`

**Comment by qxl1231** [comment]
@sebbo2002  and the file is 

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:adamgibbons/ics
BEGIN:VEVENT
UID:48236fa0-fc4e-11e7-b846-59a553b0802d
SUMMARY:enjoy it
DTSTAMP:20180118T045100Z
DTSTART:20180529T223000Z
DESCRIPTION:6666666,wonderful
URL:http://www.western.com/
GEO:40.0095;105.2669
LOCATION:shanghai, huarun Times Square ,western (lujiazui,china)
STATUS:TENTATIVE
CATEGORIES:10k races,Memorial Day Weekend,66666
ORGANIZER;CN=CN=西部证券:mailto:notification@research.xbmail.com.cn
X-MICROSOFT-CDO-IMPORTANCE:1
CLASS:PUBLIC
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;CN=龙少:mailto:qiangxiaolong@research.xbmail.com.cn
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;CN=qq:mailto:278931058@qq.com
DURATION:PT6H30M
END:VEVENT
END:VCALENDAR

```

**Comment by qxl1231** [comment]
![image](https://user-images.githubusercontent.com/8305742/35372894-23ac4a8c-01d7-11e8-89a8-635817e338ec.png)
first is wrong pic,

this is want pic ,
![image](https://user-images.githubusercontent.com/8305742/35372948-66654e3c-01d7-11e8-8eb5-e01226b1af5d.png)
