### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by krokhale** [sebbo2002/ical-generator#80]
Maybe i don't understand how iCal works, but my initial impression was that you create an event object and send it along as a string or invite.ics in your email. 

Why does one need a server? 

Any help understanding the flow is appreciated!

**Comment by sebbo2002** [comment]
That's the truth. However, it is also possible to deliver an ics file via a web server. The user can then subscribe to this URL in his or her calendar. This has the advantage that changes to this file lead to changes in the user's calendar.

This library has the method `serve()`, which is mainly intended for testing the calendar files. The method `toString()` can also be used to request the string representation. 

Please reopen the issue if you have any further questions.
