### ISSUE TITLE
htmlDescription missing from attributes in event constructor

### ISSUE THREAD

**Issue by prosomoff** [sebbo2002/ical-generator#82]
html description for body of event not working due to the value missing in attributes array.  Currently:
var attributes = ['id', 'uid', 'sequence', 'start', 'end', 'timezone', 'stamp', 'timestamp', 'allDay', 'floating', 'repeating', 'summary', 'location', 'description', 'organizer', 'attendees', 'alarms', 'method', 'status', 'url'],
        vars,
        i,
        data;
SHOULD BE:
var attributes = ['id', 'uid', 'sequence', 'start', 'end', 'timezone', 'stamp', 'timestamp', 'allDay', 'floating', 'repeating', 'summary', 'location', 'description', 'organizer', 'attendees', 'alarms', 'method', 'status', 'url','htmlDescription'],
        vars,
        i,
        data;

**Comment by sebbo2002** [comment]
Thats already fixed in `develop`, see [here](https://github.com/sebbo2002/ical-generator/blob/develop/src/event.js#L53). You'll see it live in ical-generator 3.0.

Please reopen the issue if I have misunderstood something.

**Comment by prosomoff** [comment]
All good, thanks.
