### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by KumailHussain** [sebbo2002/ical-generator#84]
I installed the package 

 **npm install ical-generator**

gives me following error

npm ERR! Unexpected end of JSON input while parsing near '...shasum":"dd07a3c8543b'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-06-29T05_40_58_347Z-debug.log
PS E:\AOTC\aotc-new> npm install ical-generator --save
npm ERR! Unexpected end of JSON input while parsing near '...shasum":"dd07a3c8543b'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-06-29T05_41_48_103Z-debug.log

**Comment by sebbo2002** [comment]
Can you please send me the content of your debug.log file in (`C:\Users\user1\AppData\Roaming\npm-cache_logs\2018-06-29T05_40_58_347Z-debug.log`)? I think it's not a problem with this particular module…

**Comment by sebbo2002** [comment]
This error occurs before downloading the module, so it's not a problem of this package. Please try to update node and npm to the current version, [clear your npm cache](https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache) and try again.
