### ISSUE TITLE
cancel event

### ISSUE THREAD

**Issue by KumailHussain** [sebbo2002/ical-generator#86]
can we cancel calendar invite?

**Comment by sebbo2002** [comment]
You can use [`status()`](https://github.com/sebbo2002/ical-generator#statusstring-status) to mark an event as cancelled.

**Comment by KumailHussain** [comment]
attendees: {"email": "a@example.com", "name": "Person A","status": "declined"}
Outlook is still showing the event

**Comment by sebbo2002** [comment]
If you do not want to show the event you have to remove it from the definition completely.

**Comment by KumailHussain** [comment]
poor documentation

for canceling an event 

method should be **cancel not request** not mentioned in the documentation

and UID should be same

**Comment by sebbo2002** [comment]
This project has not set itself the goal of explaining ical. The official documents should always be studied for this purpose. However, pull requests are always welcome for suggestions on how to improve the documentation.

**Comment by aDeadFish** [comment]
> This project has not set itself the goal of explaining ical. The official documents should always be studied for this purpose. However, pull requests are always welcome for suggestions on how to improve the documentation.



> If you do not want to show the event you have to remove it from the definition completely.

Hi! How to remove it from the definition completely?
