### ISSUE TITLE
Cancel event 

### ISSUE THREAD

**Issue by KumailHussain** [sebbo2002/ical-generator#87]
attendees: {"email": "a@example.com", "name": "Person A","status": "declined"}
and also 

event.status = 'cancelled';

Outlook is still showing the event

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
METHOD:REQUEST
NAME:Timeline Event Notifications
X-WR-CALNAME:Timeline Event Notifications
BEGIN:VEVENT
UID:1530526467079@http://aotasdt/
SEQUENCE:0
DTSTAMP:20180702T105939Z
DTSTART:20180703T094834Z
DTEND:20180703T095834Z
SUMMARY:Calendar Invite Title
LOCATION:Islamabad
DESCRIPTION:Lets check this module
ORGANIZER;CN="Kumail Hussain":mailto:kumail.hussain@123.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=DECLINED;CN="Person A":MAILTO:a@exa
 mple.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=DECLINED;CN="Person B":MAILTO:b@exa
 mple.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=DECLINED;CN="Kumail":MAILTO: kumail
 .hussain@123.com
BEGIN:VALARM
ACTION:AUDIO
TRIGGER:-PT1M
ATTACH;VALUE=URI:Basso
END:VALARM
STATUS:CANCELLED
END:VEVENT
END:VCALENDAR

**Comment by sebbo2002** [comment]
Please so not open multiple issues for the same question. I already answered your question before.

> If you do not want to show the event you have to remove it from the definition completely.
