### ISSUE TITLE
Consider using Luxon instead of Moment

### ISSUE THREAD

**Issue by radicand** [sebbo2002/ical-generator#91]
Luxon is more lightweight than Moment (especially when you factor in moment-timezone), while still maintaining most of its functionality (and more). It's made by one of the Moment maintainers and supported by that team. You can read conversion guide notes here: https://moment.github.io/luxon/docs/manual/moment.html

It's kind of a waste to bundle in moment-timezone when Luxon is able to do the zone conversions using local methods in the browser or on server. If you want to keep Moment, perhaps consider making those parts modular so as to support the option of using Luxon instead.

**Comment by Tvrqvoise** [comment]
Another option here might be to support native js Dates.  Benefits:
 - Much smaller than moment
 - Does not cause the dynamic import problems that moment does with webpack
 - Library agnostic -- every date library I'm aware of (Luxon, Moment, date-fns, dayjs) supports marshaling to and from native Date
 - Could leave back-compat for moment in the form of `if (it.isMoment) return it.toDate()` styled checks.  Therefore could be done in a minor / patch release

**Comment by sebbo2002** [comment]
@Tvrqvoise One of the first [versions of ical-generator](https://github.com/sebbo2002/ical-generator/tree/0.2.9) took this approach and used only the native Date object. Over time, however, [several time zone problems](https://github.com/sebbo2002/ical-generator/issues?q=is%3Aissue+label%3Atimezone-stuff+is%3Aclosed) appeared that could not be solved with Date. Therefore, version 2.0 was used for the moment. I am not aware that Date could map this natively.

**Comment by L-U-C-K-Y** [comment]
What could be considered is to use day.js as the api is quite similar and we will move from moment.js to date.js for our internal services.

**Comment by walmaz** [comment]
Actually, Moment.js is kinda dead - https://momentjs.com/docs/#/-project-status/

**Comment by sebbo2002** [comment]
This is one of the reasons why it is already in the [2.0 Milestone](https://github.com/sebbo2002/ical-generator/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v2.0.0+%F0%9F%8E%89%22). 😚

I plan to include support for native Date, moment.js, moment-timezone.js, Luxon and Date.js. I think that covers most of it.

**Comment by sebbo2002** [comment]
I am still ambivalent about this, but would like to clarify the issue for version 2.0.0. My current idea would be the following approach:

- ical generator works internally only with `Date` objects. Of course, these have no time zone, so everything is UTC. Of course, this does not apply if a time zone has been defined in the calendar or in the event.
- Objects from moment.js, moment-timezone.js, Luxon and Date.js could then simply be converted by ical generator into a Date object and work with that

What do you say?

**Comment by sebbo2002** [comment]
Contrary to what I originally described, I have now solved it in such a way that the original object is kept internally so that the respective library can be used to apply UTC / Timezone settings.
