### ISSUE TITLE
Repeating events in google are duplicated for the first occurrence

### ISSUE THREAD

**Issue by jamiri** [sebbo2002/ical-generator#94]
I have a repeating event and prevented it from being duplicated by writing my code as:

    const event = {}
    const now = new Date()
    event.start = now
    event.allDay = true
    event.summary = name + '\'s birthday' 
    const createdEvent = cal.createEvent(event)
    createdEvent.repeating({
        freq: 'YEARLY',
        count: 150,
        exclude: now
    })

But this causes duplicated event on the first occurrence on Google calendar.
![image](https://user-images.githubusercontent.com/1910268/43162038-1724c130-8f9f-11e8-8cee-9ee175be03c7.png)

How we can prevent this?

**Comment by sebbo2002** [comment]
I tried this locally, the ical file looks fine to me. Since I don't use Google Calendar, I can't really help there. But I can leave this issue open, maybe someone who knows the answer will come by.

**Comment by sebbo2002** [comment]
Close the issue due to inactivity. Hope the problem has been solved elsewhere.

**Comment by chriscn** [comment]
Apologies for necroposting but I was running into this issue and I'm not sure of the root cause but this was I found:

When using `express.js` if you have the following ot will duplicate the events
```node
return calendar.serve(res);
```

rather than (this is correct)
```node
calendar.serve(res);
```
