### ISSUE TITLE
Synchronisation of accept/decline

### ISSUE THREAD

**Issue by visiongeist** [sebbo2002/ical-generator#98]
This is more of a general question. How do you sync accept/decline replies of emails sent among all recipients?

**Comment by sebbo2002** [comment]
Sorry, Issue overlooked. What do you mean with "sync accept/decline replies"? Can you describe that in more detail?

**Comment by visiongeist** [comment]
if a user clicks on "accept" or "decline" the other recipients should see that in the participant list. Similar as outlook does if you create an invite on the exchange server

**Comment by sebbo2002** [comment]
You need a backend which receives the invitation reply mails, parses them and updates the attendee's status in a database or so. After that, the ical reply can be updated accordingly.

**Comment by visiongeist** [comment]
I though so. I was just hoping that there is an OOTB solution ;-)

**Comment by visiongeist** [comment]
thanks anyways for the cool library

**Comment by sebbo2002** [comment]
> I though so. I was just hoping that there is an OOTB solution ;-)

No, sorry. This is a pain unfortunately.

> thanks anyways for the cool library

Thank you. Ans sorry, for that embarrassing delay. Please ping the thread next time, so that woun't happen again.

I close this issue. Please reopen in case you have additional questions.
