### ISSUE TITLE
ICalTools.formatDate should not modify UTC

### ISSUE THREAD

**Issue by leoarnold** [sebbo2002/ical-generator#99]
This test case looks odd to me:

https://github.com/sebbo2002/ical-generator/blob/da17861d95537dddc96fa18c3c4f86296b25d984/test/test_tools.js#L38-L41

Both the input and the output date end on the letter `Z` denoting UTC, hence reformatting should not shift the time, no matter in which timezone the reformatting is performed.

**Comment by sebbo2002** [comment]
Seems like @leoarnold is right here. Have to check, why this is happening here…
